from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def replace_many(path: Path, replacements: list[tuple[str, str]]) -> bool:
    text = path.read_text(encoding="utf-8")
    original = text
    for old, new in replacements:
        text = text.replace(old, new)
    if text != original:
        path.write_text(text, encoding="utf-8")
        return True
    return False


POST_REPLACEMENTS = [
    ("Page-side POST app and API tester", "Page-side POST request app & API tester"),
    ("POST app", "POST request app"),
    ("Pure Frontend POST app", "Page-side POST request app"),
    ("Pure Frontend HTTP Request Debugging Tool", "Page-side request debugging app"),
    ("Free page-side POST app and API tester. E support HTTP methods, JSON or form data, custom headers and auth debugging for API work.",
     "Free page-side POST request app and API tester. E supports HTTP methods, JSON or form data, custom headers and auth debugging for API work."),
    ("🚀 Page-side POST app and API tester", "🚀 Page-side POST request app & API tester"),
    ("Pure page-side HTTP request debug app wey support plenty methods and data styles",
     "Pure page-side HTTP request app wey supports plenty methods and data styles for API debugging"),
    ("Page-side POST app and API tester", "Page-side POST request app & API tester"),
    ("POST app", "POST request app"),
    ("Browser POST tool and API tester", "Page-side POST app and API tester"),
    ("Preview of di page-side POST app", "Preview of di page-side POST app interface"),
    ("StarryRing Tool area", "StarryRing tool area"),
    ("Free browser POST tool and API tester, pure frontend implementation, no server required. E support HTTP methods (POST/GET/PUT/DELETE), JSON/form data, request headers configuration, authentication debugging, perfect for API development and debugging learning.",
     "Free page-side POST app and API tester. No extra server needed. E support HTTP methods, JSON or form data, custom headers and auth debugging for API work."),
    ("No, dis na a pure frontend tool dat runs completely in di browser. All requests na sent through di page Fetch API, no backend server support required.",
     "No. Dis na pure page-side app wey runs for the page. All requests dey pass through Fetch API, so no backend support needed."),
    ("Due to browser same-origin policy restrictions, cross-origin requests require di target server to configure CORS (Cross-Origin Resource Sharing) headers. If you encounter cross-origin issues, ensure di target API server has correctly configured Access-Control-Allow-Origin and other CORS headers.",
     "Because page apps follow same-origin rules, cross-origin requests need the target server to set CORS headers. If you see cross-origin wahala, make sure the API server set Access-Control-Allow-Origin and other CORS headers well."),
    ("How to Use Browser POST app to Test API Interfaces", "How to use page-side POST app to test API interfaces"),
    ("Step-by-step guide to using di page-side POST tool for API interface testing and debugging",
     "Step-by-step walk-through to use di page-side POST app for API testing and debugging"),
    ("Select HTTP method", "Choose HTTP method"),
    ("Configure request headers and body", "Set request headers and body"),
    ("Click di 'Send request' button. Di tool go send di HTTP request and display status code, response headers, and response body in di response panel.",
     "Click 'Send request'. Di page-side app go send the HTTP request and show status code, response headers and response body for the response panel."),
    ("Response result", "Response result panel"),
    ("Wetin dis tool fit do", "Wetin dis app fit help you do"),
    ("Pure frontend HTTP request debugging tool, supports multiple HTTP methods and data formats",
     "Pure page-side HTTP request debug app wey support plenty methods and data styles"),
    ("Pure Frontend Implementation", "Pure page-side setup"),
    ("Runs completely in di browser, no server required. All HTTP requests na sent through di browser Fetch API, ensuring data privacy and security.",
     "Everything runs for di page side, no extra server needed. HTTP requests dey pass through Fetch API so your setup stay private."),
    ("Multiple HTTP Methods", "Plenty HTTP methods"),
    ("E support POST, GET, PUT, DELETE, PATCH five HTTP methods, meeting basic RESTful API development needs.",
     "E support POST, GET, PUT, DELETE and PATCH for normal REST API work."),
    ("Multi-format Data Support", "Plenty data styles"),
    ("E support JSON and form data formats, convenient for testing different types of API interfaces. JSON editor provides syntax highlighting and validation.",
     "E support JSON and form data so you fit test different API styles. JSON editor still helps with format and validation."),
    ("Custom Request Headers", "Custom request headers"),
    ("Flexibly configure request headers, supports common headers like Content-Type, Authorization, User-Agent, meeting complex API testing requirements.",
     "You fit set headers like Content-Type, Authorization and User-Agent when the API need extra control."),
    ("URL History Record", "URL history"),
    ("Automatically saves recently used URLs, convenient for quick switching and repeated testing, improving debugging efficiency.",
     "E saves recent URL list so you fit switch quick and test again without typing everything."),
    ("Frequently Asked Questions", "Question people dey ask well well"),
    ("Usage Tips", "Helpful tips"),
    ("Use shortcut Ctrl+Enter (Windows) or Cmd+Enter (Mac) to quickly send requests",
     "Use Ctrl+Enter or Cmd+Enter if you wan send request fast"),
    ("JSON data na automatically formatted for easy reading and editing",
     "JSON data fit arrange itself make reading and editing easy"),
    ("Response data fit copy go clipboard for more checking",
     "You fit copy response data go clipboard for more check"),
    ("For local development, recommended URL format: http://localhost:port",
     "For local work, URL like http://localhost:port dey easiest"),
    ("Save frequently used API configurations for quick repeated testing",
     "Keep the API setup wey you use often so repeat testing go quick"),
    ("Pure Frontend POST Tool", "Page-side POST request app"),
    ("Pure Frontend HTTP Request Debugging Tool", "Page-side request debugging app"),
    ("Pure frontend HTTP request debug app wey support plenty methods and data styles", "Pure page-side HTTP request app wey supports plenty methods and data styles for API debugging"),
    ("Request setup", "Request setup panel"),
    ("Request URL", "Request URL address"),
    ("Request method", "HTTP method"),
    ("Request body type", "Request body style"),
    ("Send request", "Send request now"),
    ("Live Response Preview", "Live response preview"),
    ("Does dis tool support HTTPS?", "Does dis app support HTTPS?"),
    ("Na data saved to di server?", "Na data saved to server?"),
    ("Pure Frontend POST app", "Page-side POST request app"),
]


WEBSOCKET_REPLACEMENTS = [
    ("Page-side WebSocket tester", "Page-side WebSocket test app"),
    ("Free page-side WebSocket tester. E support WS/WSS connection, custom headers, message stats, templates and log search. No download, quick debugging.",
     "Free page-side WebSocket test app. E supports WS/WSS connection, custom headers, message stats, templates and log search. No download, quick debugging."),
    ("Free page-side WebSocket tester. E support WS/WSS connection, custom headers, message stats, templates and quick debugging.",
     "Free page-side WebSocket test app. E supports WS/WSS connection, custom headers, message stats, templates and quick debugging."),
    ("⚡ Page-side WebSocket tester: enter server address, connect and start message work. E support custom headers, templates, live stats and log filtering. No download, quick debugging.",
     "⚡ Page-side WebSocket test app: enter server address, connect and start message work. E supports custom headers, templates, live stats and log filtering. No download, quick debugging."),
    ("WebSocket tester interface", "WebSocket test app interface"),
    ("WebSocket tester", "WebSocket test app"),
    ("Page-side WebSocket tester", "Page-side WebSocket test app"),
    ("Page-side WebSocket test tool - free WS/WSS client | StarryRing", "Page-side WebSocket tester - free WS/WSS client | StarryRing"),
    ("Page-side WebSocket test tool", "Page-side WebSocket tester"),
    ("WebSocket test tool interface", "WebSocket tester interface"),
    ("WebSocket connection test interface", "WebSocket connection test screen"),
    ("WebSocket connection config and messaging interface", "WebSocket connection setup and message screen"),
    ("Free page-side WebSocket testing tool. E support WS/WSS connections, custom headers, message stats, templates, log search. No download, fast debugging.",
     "Free page-side WebSocket tester. E support WS/WSS connection, custom headers, message stats, templates and log search. No download, quick debugging."),
    ("Free page-side WebSocket testing tool. E support WS/WSS connections, custom headers, message stats, templates, fast debugging.",
     "Free page-side WebSocket tester. E support WS/WSS connection, custom headers, message stats, templates and quick debugging."),
    ("WebSocket na a protocol providing full-duplex communication over a single TCP connection, allowing servers to push data to clients. Dis tool helps test if your WebSocket service works correctly.",
     "WebSocket na protocol wey allows two-way communication on one TCP connection, so server fit push data come your side. Dis tester helps you check whether your WebSocket service dey work well."),
    ("Enter di WebSocket server URL (e.g. wss://echo.websocket.org), click 'Connect'. Once e connect, type message for the input side and click 'Send'. You go see reply for the log.",
     "Enter the WebSocket server URL, click 'Connect', then type message and click 'Send'. Reply go show for the log."),
    ("For 'Connection setup', click '+ Add' if you wan put header name and value. Dese headers na sent during di WebSocket handshake, useful for authentication or custom parameters.",
     "For 'Connection setup', click '+ Add' if you wan put header name and value. The headers go join the WebSocket handshake and fit help with auth or custom parameters."),
    ("Text, JSON, and Hex. Select di format, enter your content, and it go be converted automatically. JSON mode includes format and minify buttons for easy editing.",
     "Text, JSON and Hex. Choose the format, enter your content, and the page go arrange am. JSON mode still get format and minify buttons for easier editing."),
    ("WebSocket Page-side Test Tool", "Page-side WebSocket test app"),
    ("⚡ Page-side WebSocket tester: enter server address, click connect and start messaging. E support custom headers, templates, live stats & log filtering. No download, fast debugging.",
     "⚡ Page-side WebSocket test app: enter server address, connect and start message work. E supports custom headers, templates, live stats and log filtering. No download, quick debugging."),
    ("⚡ Page-side WebSocket tester: enter server address, connect and start message work. E support custom headers, templates, live stats and log filtering. No download, quick debugging.",
     "⚡ Page-side WebSocket test app: enter server address, connect and start message work. E supports custom headers, templates, live stats and log filtering. No download, quick debugging."),
    ("WebSocket Terminal", "WebSocket tester"),
    ("Connection Settings", "Connection setup"),
    ("Message Statistics", "Message stats"),
    ("Preset Endpoints", "Preset endpoints"),
    ("Live connection latency measurement", "Live connection delay reading"),
    ("WebSocket tester interface", "WebSocket test app interface"),
    ("Connect</button>", "Connect now</button>"),
    ("Disconnect</button>", "Disconnect now</button>"),
    ("History</span>", "Old list</span>"),
    ("Message Log", "Message log"),
    ("Pro WebSocket test Wetin dis tool fit do", "Pro WebSocket test wetin dis app fit do"),
]


KEYBOARD_REPLACEMENTS = [
    ("Page-side Keyboard check page", "Page-side keyboard test page"),
    ("Keyboard check page", "Keyboard test page"),
    ("Page-side Keyboard check page - Chatter, NKRO & response test | StarryRing", "Page-side keyboard test page - chatter, NKRO & response test | StarryRing"),
    ("Page-side Keyboard check page - Chatter, NKRO &amp; Response Test", "Page-side keyboard test page - chatter, NKRO &amp; response test"),
    ("Free page-side keyboard check page. Test key chatter, double hit, response delay and NKRO with live feedback and quick repair hints.",
     "Free page-side keyboard test page. Test key chatter, double hit, response delay and NKRO with live feedback and quick repair hints."),
    ("Free page-side keyboard check page. Test chatter, double hit, response delay and NKRO for all keyboard types.",
     "Free page-side keyboard test page. Test chatter, double hit, response delay and NKRO for all keyboard types."),
    ("Free page-side keyboard check page. Test chatter, double hit, response delay and NKRO.",
     "Free page-side keyboard test page. Test chatter, double hit, response delay and NKRO."),
    ("Page-side Keyboard check page", "Page-side keyboard test page"),
    ("Keyboard check page", "Keyboard test page"),
    ("Browser Keyboard Checker - Chatter, NKRO &amp; Response Test | StarryRing", "Page-side Keyboard Checker - Chatter, NKRO & response test | StarryRing"),
    ("Preview of di browser keyboard checker layout", "Preview of di page-side keyboard checker layout"),
    ("Browser keyboard checker interface preview", "Preview of di page-side keyboard checker"),
    ("Starry Tool", "StarryRing"),
    ("StarryRing Tool area", "StarryRing tool area"),
    ("Keyboard Checker", "Keyboard check page"),
    ("Keyboard checker", "Keyboard check page"),
    ("Browser Keyboard Checker", "Page-side Keyboard Checker"),
    ("Free browser keyboard checker. Test key chatter, double hit, response delay and NKRO with live feedback and repair hints.",
     "Free page-side keyboard check page. Test key chatter, double hit, response delay and NKRO with live feedback and quick repair hints."),
    ("Free browser keyboard checker. Test chatter, double hit, response delay and NKRO for all keyboard types.",
     "Free page-side keyboard check page. Test chatter, double hit, response delay and NKRO for all keyboard types."),
    ("Free browser keyboard checker. Test chatter, double hit, response delay and NKRO.",
     "Free page-side keyboard check page. Test chatter, double hit, response delay and NKRO."),
    ("Free browser keyboard checker for chatter, response delay, NKRO and repair hints.",
     "Free page-side keyboard check page for chatter, response delay, NKRO and repair hints."),
    ("How do I detect keyboard chattering (double-click issue)?", "How I go spot keyboard chatter (double-hit wahala)?"),
    ("Mild chattering, early aging", "Small chatter, early aging"),
    ("Moderate chattering &ndash; needs cleaning/repair", "Middle chatter &ndash; e need cleaning or repair"),
    ("Severe chattering, debounce failure", "Heavy chatter, debounce fail"),
    ("Single switch/trace damaged", "One switch or trace don spoil"),
    ("How to use di keyboard checker", "How to use di keyboard check page"),
    ("Keyboard checker FAQ", "Keyboard check page FAQ"),
    ("Dis browser keyboard checker helps you find common keyboard wahala like fast repeat, chatter, double hit, slow response and NKRO limits. E also gives quick repair hints.",
     "Dis page-side keyboard check page helps you find common keyboard wahala like fast repeat, chatter, double hit, slow response and NKRO limits. E also gives quick repair hints."),
    ("Tool area", "Tool page hub"),
]


PASSWORD_REPLACEMENTS = [
    ("secure random password tool", "secure random password app"),
    ("CyberPass Pro - page-side password maker | secure random password tool | StarryRing",
     "CyberPass Pro - page-side password maker | secure random password app | StarryRing"),
    ("Free page-side password maker wey fit create strong random passwords. E get character control, live strength check and batch generation to keep account safe.",
     "Free page-side password maker wey fit create strong random passwords. E gets character control, live strength check and batch generation to help keep account safe."),
    ("CyberPass Pro na page-side password maker wey fit create strong random passwords. E get character control, live strength check and batch generation to keep account safe.",
     "CyberPass Pro na page-side password maker wey fit create strong random passwords. E gets character control, live strength check and batch generation to help keep account safe."),
    ("Create strong random passwords | Character control | Live strength check",
     "Make strong random passwords | Character control | Live strength check"),
    ("secure random password tool", "secure random password app"),
    ("CyberPass Pro password generator interface - professional page-side password generator tool",
     "CyberPass Pro interface - pro page-side password maker"),
    ("CyberPass Pro - page-side password generator | secure random password tool | StarryRing",
     "CyberPass Pro - page-side password maker | secure random password tool | StarryRing"),
    ("CyberPass Pro - Pro page-side password generator", "CyberPass Pro - pro page-side password maker"),
    ("CyberPass Pro - Page-side Password generator", "CyberPass Pro - page-side password maker"),
    ("CyberPass Pro - password generator", "CyberPass Pro - password maker"),
    ("CyberPass Pro password generator", "CyberPass Pro password maker"),
    ("No-pay tool wey you fit use page-side password generator, create high-strength, secure random passwords. Full character-level control, live strength analysis, and batch generation for enhanced account security. No-pay live password generation tool.",
     "CyberPass Pro na page-side password maker wey fit create strong random passwords. E get character control, live strength check and batch generation to keep account safe."),
    ("No-pay tool wey you fit use page-side password generator, create high-strength, secure random passwords. Full character-level control, live strength analysis, and batch generation to keep your accounts safe.",
     "Free page-side password maker wey fit create strong random passwords. E get character control, live strength check and batch generation to keep account safe."),
    ("No-pay tool wey you fit use page-side password generator, create high-strength, secure random passwords. Character-level control, strength analysis, batch generation.",
     "Free page-side password maker wey fit create strong random passwords. E get character control, strength check and batch generation."),
    ("No-pay tool wey you fit use page-side password generator, create high-strength, secure random passwords. Character-level control, password strength analysis, batch generation for enhanced account security.",
     "Free page-side password maker wey fit create strong random passwords. E get character control, strength check and batch generation."),
    ("CyberPass Pro na a professional page-side password generation tool dat creates high-strength, secure random passwords. It offers precise character-level control, live strength analysis, and multiple preset modes to help users generate unguessable passwords.",
     "CyberPass Pro na pro page-side password maker wey fits create strong random passwords. E gives precise character control, live strength check and plenty preset modes to help people generate hard-to-guess passwords."),
    ("Use guide am am am am di character selector feature?", "How I fit use the character picker feature?"),
    ("The character selector allows you to precisely control which characters na included or excluded from your password. You fit toggle individual characters or use 'Include all' / 'Remove all' buttons. Dis helps avoid ambiguous characters (like 0 and O, 1 and l) and improves password readability.",
     "The character picker lets you control which characters go enter or stay out of your password. You fit switch one-one or use 'Include all' and 'Remove all'. E helps avoid confusing pairs like 0 and O, or 1 and l."),
    ("Step-by-step guide to generate high-strength passwords with CyberPass Pro",
     "Step-by-step guide to generate strong passwords with CyberPass Pro"),
    ("Select a preset mode: click 'High Strength', 'Easy Input', 'PIN Code', or 'Memorable' button",
     "Pick one preset mode: 'High Strength', 'Easy Input', 'PIN Code' or 'Memorable'"),
    ("Generate password: click 'Generate New Password' button, view password and strength analysis",
     "Generate password: click 'Generate New Password', then check the password and strength result"),
    ("Copy or export: click copy button to save password to clipboard, or use export function",
     "Copy or export: use the copy side to save am to clipboard, or use export if you need file"),
    ("Character Selector", "Character picker"),
    ("Character Selector Interface", "Character picker screen"),
    ("E show character-level control and exclusion options", "E show character control and remove options"),
    ("Password Generation Interface", "Password making screen"),
    ("High-strength password generation (6-64 characters)", "Strong password generation (6-64 characters)"),
    ("Character-level precise control (include/exclude specific characters)", "Precise character control (include or remove any character)"),
    ("Live password strength analysis and entropy calculation", "Live password strength check and entropy reading"),
    ("Batch password generation (generate 5 at once)", "Batch password generation (make 5 at once)"),
    ("Password crack time estimation", "Password crack-time estimate"),
    ("Export and copy functionality", "Export and copy support"),
    ("Include All", "Include all"),
    ("Exclude All", "Remove all"),
    ("Reset Default", "Reset default"),
    ("Uppercase (A-Z)", "Big letters (A-Z)"),
    ("Lowercase (a-z)", "Small letters (a-z)"),
    ("Password Analysis", "Password check"),
    ("Available charset:", "Available set:"),
    ("Excluded chars:", "Removed chars:"),
    ("Export Passwords", "Export passwords"),
    ("Copy Password", "Copy password"),
    ("Security Tips", "Security hints"),
    ("Question people dey ask well well (FAQ)", "Question people dey ask well well"),
    ("What na password entropy and why does it matter?", "Wetin be password entropy and why e matter?"),
    ("Why would I exclude certain characters?", "Why person go remove some characters?"),
    ("Na generated passwords truly secure?", "Generated password truly secure?"),
    ("How suppose I save generated passwords?", "How I suppose keep generated passwords?"),
    ("Na dis tool free?", "Dis tool free?"),
    ("Can I export generated passwords?", "I fit export generated passwords?"),
    ("Create high-strength, secure random passwords | Character-level control | Live strength analysis",
     "Create strong random passwords | Character control | Live strength check"),
    ("Create strong random passwords | Character control | Live strength check", "Make strong random passwords | Character control | Live strength check"),
    ("Overview: Pro page-side password generator with character-level control, live strength analysis, and multiple preset modes. Seamless integration of<strong>password generator</strong>, <strong>random password</strong>, and<strong>password strength analysis</strong>.",
     "Overview: Pro page-side password maker with character control, live strength check and many preset modes. E joins <strong>password making</strong>, <strong>random password</strong> and <strong>password strength analysis</strong>."),
    ("Generating secure password...", "Dey generate secure password..."),
    ("Calculating strength...", "Dey calculate strength..."),
    ("Password generator", "Password maker"),
    ("Generate New Password", "Generate new password"),
    ("Batch Generate", "Batch generate"),
    ("Must Contain", "Must contain"),
    ("High Strength", "Strong pass"),
    ("Easy Input", "Easy type"),
    ("PIN Code", "PIN code"),
    ("Memorable", "Easy remember"),
    ("Password length", "Password size"),
    ("Generate new password", "Make new password"),
    ("Batch generate (5)", "Make 5 at once"),
]


TOOLBOX_INDEX_REPLACEMENTS = [
    ("Browser hardware check tools for mouse, keyboard, camera and mic", "Page-side hardware test tools for mouse, keyboard, camera and mic"),
    ("Browser hardware check tools for mouse, keyboard, camera, microphone, speaker, and screen.",
     "Page-side hardware test tools for mouse, keyboard, camera, microphone, speaker and screen."),
    ("Browser hardware test suite for mouse, keyboard, camera, microphone, speaker, and screen. Free to use and no download needed.",
     "Full page-side hardware test set for mouse, keyboard, camera, microphone, speaker and screen. Free to use, no download needed."),
    ("HardwareTest Pro", "HardwareTest Pro page-side lab"),
    ("Toolbox", "Tool page hub"),
    ("Professional<span class=\"highlight\">browser hardware lab</span>.",
     "Professional <span class=\"highlight\">page-side hardware lab</span>."),
    ("title=\"Browser mouse check tool\"", "title=\"Page-side mouse test page\""),
    ("title=\"Browser Keyboard checking Tool\"", "title=\"Page-side keyboard test page\""),
    ("title=\"Browser Camera checking Tool\"", "title=\"Page-side camera test page\""),
    ("title=\"Browser Microphone checking Tool\"", "title=\"Page-side mic test page\""),
    ("title=\"Browser Screen Dead pixel testing Tool\"", "title=\"Page-side screen test page\""),
    ("title=\"Browser speaker checking Tool\"", "title=\"Page-side speaker test page\""),
    ("HardwareTest guide and wetin e fit do", "HardwareTest guide and wetin e fit do well"),
    ("Wetin mouse test fit do", "Wetin mouse test page fit do"),
    ("Wetin keyboard test fit do", "Wetin keyboard test page fit do"),
    ("Wetin camera test fit do", "Wetin camera test page fit do"),
    ("Wetin mic test fit do", "Wetin mic test page fit do"),
]


RANDOM_NUMBER_REPLACEMENTS = [
    ("CyberNum Random number generator Interface Screenshot - Pro Browser Random Number Tool",
     "CyberNum random number maker interface screenshot - pro page-side random number app"),
    ("CyberNum - random number engine", "CyberNum random number maker"),
    ("Pro page-side random number generator, supports integer, decimal, custom range random number generation, with batch generation, uniqueness check, history features",
     "Pro page-side random number maker wey supports whole number, decimal and custom range number making, plus batch mode, uniqueness check and old-record support"),
    ("CyberNum Random number generator Interface", "CyberNum random number maker interface"),
    ("Random Number Generation Interface", "Random number making screen"),
    ("History Management Interface", "Old-record management screen"),
    ("What na CyberNum random number engine?", "Wetin be CyberNum random number maker?"),
    ("CyberNum na a professional page-side random number generator dat supports multiple random number generation modes, including integer mode, decimal mode, and custom range mode. It provides batch generation, uniqueness check, history features, suitable for lottery, testing, password generation, and various other scenarios.",
     "CyberNum na pro page-side random number maker wey fit produce whole numbers, decimals and custom range numbers. E gets batch making, uniqueness check and old-record support, so e good for lottery, testing, password work and many other tasks."),
    ("How to Generate Random Number Sequences with CyberNum", "How to make random number list with CyberNum"),
    ("Step-by-step guide on using CyberNum random number engine to generate random number sequences",
     "Step-by-step walk-through on how to use CyberNum random number maker to build random number lists"),
    ("CyberNum - browser random number engine for integer, decimal, and custom range | StarryRing",
     "CyberNum - page-side random number maker for whole number, decimal and custom range | StarryRing"),
    ("CyberNum - Pro page-side random number generator, supports integer, decimal, custom range random number generation, with batch generation, uniqueness check, history features. No-pay random number generator for lottery, testing, password generation, etc.",
     "CyberNum na pro page-side random number maker for whole number, decimal and custom range. E gets batch making, uniqueness check and old-record support. Free to use for lottery, testing, password work and more."),
    ("CyberNum - Pro Browser random number engine | StarryRing", "CyberNum - pro page-side random number maker | StarryRing"),
    ("CyberNum - Browser random number engine", "CyberNum - page-side random number maker"),
    ("No-pay tool wey you fit use page-side random number generator, supports integer, decimal, custom range random number generation, batch generation, uniqueness check, history features",
     "Free page-side random number maker wey supports whole number, decimal and custom range number making, batch mode, uniqueness check and old-record support"),
    ("random number generator, page-side random number tool, random number generation, random number picker, random number test, batch random number generation, random number tool, random number engine",
     "random number maker, page-side random number app, random number list, random number picker, batch random number making, custom range random number"),
    ("CyberNum - Pro random number engine", "CyberNum - pro random number maker"),
    ("CyberNum random number engine Wetin e fit do", "CyberNum random number maker wetin e fit do"),
    ("📖 Intro: Pro random number generator, supports multiple random number generation modes, provides batch generation, uniqueness check, history features. Perfect integration of<strong>random number generator</strong>, <strong>page-side random number tool</strong>, <strong>random number picker</strong>functions.",
     "📖 Intro: Pro random number maker wey supports plenty number-making modes, batch making, uniqueness check and old-record support. E joins <strong>random number maker</strong>, <strong>page-side random number app</strong> and <strong>random number picker</strong> work together."),
    ("Yes, CyberNum random number engine na completely free page-side tool, no registration or login required. We na committed to providing high-quality free tools for developers and general users, helping improve work and study efficiency. All features na free to use, with no hidden fees or limitations.",
     "Yes, CyberNum random number maker na fully free page-side tool. No register or login needed. All the features dey open, with no hidden payment or usage limit."),
    ("© 2024 StarryRing - CyberNum random number engine", "© 2024 StarryRing - CyberNum random number maker"),
]


SPEAKER_REPLACEMENTS = [
    ("Browser Speaker Checker - Full Frequency &amp; Channel Balance Test | StarryRing",
     "Page-side speaker test page - full frequency &amp; channel balance check | StarryRing"),
    ("Browser Speaker Checker", "Page-side speaker test page"),
    ("Browser speaker checker with 10Hz-21kHz sweep, channel balance test and noise test.",
     "Page-side speaker test page with 10Hz-21kHz sweep, channel balance check and noise test."),
    ("Free browser speaker checker for 10Hz-21kHz sweep, channel balance and noise test. Check frequency response for speakers, headphones and home theater systems.",
     "Free page-side speaker test page for 10Hz-21kHz sweep, channel balance and noise test. Check frequency response for speakers, headphones and home theater systems."),
    ("Free browser speaker checker with 10Hz-21kHz sweep, channel balance and noise test.",
     "Free page-side speaker test page with 10Hz-21kHz sweep, channel balance and noise test."),
    ("Browser Speaker Checker - Full Frequency &amp; Channel Balance Test",
     "Page-side speaker test page - full frequency &amp; channel balance check"),
    ("Browser Speaker Checker - Full Frequency Test", "Page-side speaker test page - full frequency check"),
    ("speaker checker, browser speaker test, frequency sweep, channel balance test, headphone test, white noise test",
     "speaker test page, page-side speaker test, frequency sweep, channel balance check, headphone test, white noise test"),
    ("Tool area", "Tool page hub"),
    ("Speaker Checker", "Speaker test page"),
    ("<h1><i class=\"fas fa-wave-square\"></i>Browser Speaker Checker</h1>",
     "<h1><i class=\"fas fa-wave-square\"></i>Page-side speaker test page</h1>"),
    ("Live spectrum analysis", "Live spectrum check"),
    ("Test frequency", "Test frequency level"),
    ("Start playback", "Start playback now"),
    ("Stop all", "Stop everything"),
    ("Left side", "Left speaker"),
    ("Both sides", "Both speakers"),
    ("Right side", "Right speaker"),
    ("Current frequency", "Current frequency level"),
    ("Wetin dis speaker checker fit help you do", "Wetin dis speaker test page fit help you do"),
    ("Audio testing tool", "Audio test app"),
    ("Browser acoustic measurement", "Page-side sound check"),
    ("© 2026 StarryRing · Browser Speaker Checker", "© 2026 StarryRing · Page-side speaker test page"),
]


PING_REPLACEMENTS = [
    ("Browser network pulse checker", "Page-side network pulse checker"),
    ("Free browser network checker: ICMP ping through remote proxy and HTTPS GET direct from browser, with latency, packet loss and jitter tracking.",
     "Free page-side network checker: ICMP ping through remote proxy and HTTPS GET direct from your page, with latency, packet loss and jitter tracking."),
    ("Browser network diagnostics tool supporting ICMP Ping via remote proxy and HTTPS GET directly from browser. Real‑time latency, packet loss, jitter. No-pay, no download, test your network stability now.",
     "Page-side network check tool wey supports ICMP Ping through remote proxy and HTTPS GET direct from your page. Live latency, packet loss and jitter. Free, no download, test your network stability now."),
    ("Network Pulse - Browser Ping &amp; HTTPS Test Tool | StarryRing",
     "Network Pulse - page-side Ping &amp; HTTPS test page | StarryRing"),
    ("Network Pulse - Real‑time Ping &amp; HTTPS Test Tool", "Network Pulse - live Ping &amp; HTTPS test page"),
    ("Free browser network diagnostics: ICMP Ping via remote proxy or HTTPS GET from your browser. Accurate latency, loss, jitter with history and live charts.",
     "Free page-side network diagnostics: ICMP Ping through remote proxy or HTTPS GET from your page. Accurate latency, loss and jitter with old records and live charts."),
    ("Free browser network diagnostics: measure latency, loss, jitter with live charts and terminal log.",
     "Free page-side network diagnostics: measure latency, loss and jitter with live charts and terminal log."),
    ("Ping test, HTTPS test, network latency, network diagnostics, page-side ping tool, packet loss, jitter test, network stability",
     "Ping test, HTTPS test, network latency, network diagnostics, page-side ping page, packet loss, jitter test, network stability"),
    ("ICMP Ping test interface", "ICMP Ping test screen"),
    ("HTTPS GET test interface", "HTTPS GET test screen"),
    ("Network Diagnostics Tool", "Network pulse test page"),
]


APP_ICON_REPLACEMENTS = [
    ("Browser app icon generator screen", "Page-side app icon maker screen"),
    ("Browser app icon generator | StarryRing", "Page-side app icon maker | StarryRing"),
    ("Browser app icon generator", "Page-side app icon maker"),
    ("Free browser app icon generator. Create iOS and Android icon sizes, preview them live, crop image well and export everything together.",
     "Free page-side app icon maker. Create iOS and Android icon sizes, preview them live, crop image well and export everything together."),
    ("Dis browser app icon generator help mobile app developers create different icon sizes for iOS and Android fast-fast, with live preview so everything fit show well on devices.",
     "Dis page-side app icon maker helps mobile app developers create different icon sizes for iOS and Android fast-fast, with live preview so everything fit show well on devices."),
    ("How to generate app icons with dis browser tool", "How to make app icons with dis page-side app"),
    ("Browser tool wey fit generate app icon, preview am for iOS and Android, and export the whole icon set together.",
     "Page-side tool wey fit make app icon, preview am for iOS and Android, and export the whole icon set together."),
    ("Wetin dis browser app icon generator fit do", "Wetin dis page-side app icon maker fit do"),
    ("🎨 Browser tool wey fit generate iOS and Android app icons with live preview, smart crop and batch export.",
     "🎨 Page-side tool wey fit make iOS and Android app icons with live preview, smart crop and batch export."),
    ("Browser app icon generator – one place for your icon work", "Page-side app icon maker – one place for your icon work"),
    ("Browser app icon generator | Last updated: Jan 2026 | Version: v1.1.0", "Page-side app icon maker | Last updated: Jan 2026 | Version: v1.1.0"),
]


IMAGE_CONVERTER_REPLACEMENTS = [
    ("Image resize and convert tool - private browser studio | StarryRing", "Image resize and convert app - private page-side studio | StarryRing"),
    ("Private browser image studio screen shot", "Private page-side image studio screen shot"),
    ("Private browser image studio", "Private page-side image studio"),
    ("Free browser tool wey fit resize and convert image. Change image size, width, height, ratio and format like PNG, JPG, WebP, HEIC, TIFF, BMP and SVG. Everything dey run for your browser, no upload.",
     "Free page-side tool wey fit resize and convert image. Change image size, width, height, ratio and format like PNG, JPG, WebP, HEIC, TIFF, BMP and SVG. Everything dey run for your page side, no upload."),
    ("Dis private browser image studio fit resize image, adjust size and convert between PNG, JPG, WebP, HEIC, TIFF, BMP and SVG. Everything happens locally on your device, so your file no leave your hand.",
     "Dis private page-side image studio fit resize image, adjust size and convert between PNG, JPG, WebP, HEIC, TIFF, BMP and SVG. Everything happens locally on your device, so your file no leave your hand."),
    ("Absolutely not. All image processing na done locally in your browser using pure front-end technologies. Your images never leave your device, providing di highest level of privacy.",
     "Absolutely not. All image processing dey happen locally for your page using pure front-end setup. Your images never leave your device, so privacy stay high."),
    ("How to resize and convert image with dis private browser studio", "How to resize and convert image with dis private page-side studio"),
    ("Free browser tool wey fit resize and convert image. Change width, height, ratio and format like PNG, JPG, WebP, HEIC, TIFF, BMP and SVG. Everything dey run locally, no upload.",
     "Free page-side tool wey fit resize and convert image. Change width, height, ratio and format like PNG, JPG, WebP, HEIC, TIFF, BMP and SVG. Everything dey run locally, no upload."),
]


CAMERA_EXTRA_REPLACEMENTS = [
    ("Camera Checker", "Camera test page"),
    ("camera checker, browser camera test, webcam sharpness test, resolution test, FPS test, laptop camera checker, USB camera checker",
     "camera test page, page camera test, webcam sharpness test, resolution test, FPS test, laptop camera test, USB camera test"),
    ("Tool area", "Tool page hub"),
    ("Free tool for browser", "Free page-side app"),
    ("Dis browser camera checker no need installation.", "Dis page-side camera checker no need installation."),
    ("Browser and driver read dis data", "Page and control app read dis data"),
    ("Main better side of dis camera checker", "Main better side of dis camera test page"),
    ("Wetin dis camera checker fit do", "Wetin dis camera test page fit do"),
    ("Overview: Dis camera checker gives you full camera test, from basic live video up to deeper performance reading, so you fit know how your camera dey behave.",
     "Overview: Dis camera test page gives you full camera check, from basic live video up to deeper performance reading, so you fit know how your camera dey behave."),
]


MIC_EXTRA_REPLACEMENTS = [
    ("Microphone Checker", "Microphone test page"),
    ("Tool area", "Tool page hub"),
    ("Page-side Microphone Checker", "Page-side Microphone test page"),
    ("Mic Checker", "Mic test page"),
    ("Wetin dis microphone checker fit do", "Wetin dis microphone test page fit do"),
    ("📖 Intro: Dis microphone checker gives you full audio test from simple volume check to deeper spectrum reading, so you fit know how your mic dey behave.",
     "📖 Intro: Dis microphone test page gives you full audio test from simple volume check to deeper spectrum reading, so you fit know how your mic dey behave."),
    ("Accurately measure latency from microphone input to playback output. Crucial for recording, live streaming, and live communication applications.",
     "E measures delay from microphone input to playback output. E useful for recording, live streaming and live communication work."),
    ("E support all types of audio input devices, automatically detects available microphones in di system. One-click switching between different microphones.",
     "E supports all audio input device types, automatically spots available microphones for the system, and lets you switch with one tap."),
]


MOUSE_INSTRUCTION_REPLACEMENTS = [
    ("Use the data panel and event record to judge the mouse condition.", "Use the data panel and event record to judge the mouse look."),
    ("Use the double-tap spotting feature. If red faulty double-tap highlight dey show often, e usually means the mouse micro-switch fit don age.",
     "Use the double-tap spotting feature. If red faulty double-tap highlight dey show often, e usually means the mouse micro-switch fit don old."),
    ("Does dis tool require software installation?", "Dis page need app install?"),
    ("mouse check page walk-through, mouse side check, scroll wheel check, double-tap fault, mouse troubleshooting, hardware check",
     "mouse check page walk-through, mouse side test, scroll wheel test, double-tap wahala, mouse troubleshooting, hardware check"),
    ("without installing any software", "without installing any app"),
    ("Note:</strong>Some side sides fit depend on driver for full function, but basic side answer should still show here.",
     "Note:</strong>Some side sides fit depend on control app for full function, but basic side answer should still show here."),
    ("Install official mouse driver, try another page app, and check side-side settings inside the mouse app.",
     "Install official mouse control app, try another page, and check side-side settings inside the mouse app."),
]


DOUBLE_CLICK_INSTRUCTION_REPLACEMENTS = [
    ("faulty double-tap wahala spotting", "faulty double-tap spotting"),
    ("Tap di left mouse side two times at normal speed, around 200-500ms apart. If everything dey okay, the side area go show green highlight and the log go record normal double tap.",
     "Tap the left mouse side two times at normal speed, around 200-500ms apart. If everything dey okay, the side area go show green highlight and the log go record normal double-tap."),
    ("If one single press dey often register like two extremely fast taps, the page go mark am as faulty double-tap wahala. Red highlight and log entry go help you notice am.",
     "If one single press dey often register like two extremely fast taps, the page go mark am as faulty double-tap. Red highlight and log entry go help you notice am."),
    ("Why dis matter:</strong>Frequent faulty double-tap wahala usually means the micro-switch don age and fit soon need cleaning, repair, or replacement.",
     "Why dis matter:</strong>Frequent faulty double-tap usually means the micro-switch don age and fit soon need cleaning, repair or replacement."),
    ("Some side count no rise, press/release counts no match, wheel fails in one direction, or faulty double-tap wahala keeps showing too often.",
     "Some side count no rise, press/release counts no match, wheel fails in one direction, or faulty double-tap keeps showing too often."),
]


FAVICON_REPLACEMENTS = [
    ("Favicon Studio Pro interface screenshot - Pro page-side Favicon generator", "Favicon Studio Pro screenshot - page-side favicon maker"),
    ("Favicon Studio Pro - Favicon Generator", "Favicon Studio Pro - favicon maker"),
    ("No-pay tool wey you fit use page-side Favicon generator with native browser ICO conversion. Fully local processing, generates multi-resolution ICO, Apple Touch Icon, Android Chrome icons, complete PWA icon kit.",
     "Free page-side favicon maker with native ICO conversion. Everything runs locally and e fit make ICO, Apple Touch Icon, Android Chrome icons and full PWA icon pack."),
    ("Favicon Studio Pro Interface", "Favicon Studio Pro interface"),
    ("Favicon Generation Interface", "Favicon making screen"),
    ("E show image upload, cropping, and preview features", "E show image upload, crop and preview parts"),
    ("Device Preview Interface", "Device preview screen"),
    ("E show icon preview effects in iOS, Android, and Web browsers", "E show how icon go look for iOS, Android and page apps"),
    ("Fully local processing (no server upload)", "Everything dey run local (no server upload)"),
    ("Browser-native ICO generation (16×16, 32×32, 48×48)", "Page-native ICO making (16×16, 32×32, 48×48)"),
    ("SVG vector icon generation", "SVG vector icon making"),
    ("Apple Touch Icon generation (180×180)", "Apple Touch Icon making (180×180)"),
    ("Android Chrome icon generation (192×192, 512×512)", "Android Chrome icon making (192×192, 512×512)"),
    ("Web Manifest file auto-generation", "Web Manifest file auto creation"),
    ("Live device preview (iOS, Android, browser)", "Live device preview (iOS, Android, page app)"),
    ("Image cropping and editing tools", "Image crop and edit tools"),
    ("Batch download ZIP package (complete icon kit)", "Batch ZIP download (full icon pack)"),
]


UTILITY_INDEX_REPLACEMENTS = [
    ("Useful tools &ndash; Browser helper corner wey fit save your time", "Useful tools &ndash; Page-side helper corner wey fit save your time"),
    ("Collection of useful browser tools wey help you handle design, math, and dev work faster without stress.",
     "Collection of useful page-side tools wey fit help you handle design, math and dev work faster without stress."),
    ("Collection of browser tools wey fit help your work move faster. Open any one with one click.",
     "Collection of page-side tools wey fit help your work move faster. Open any one with one click."),
    ("Utility tools", "Useful tools"),
    ("Browser voice recorder", "Page-side voice recorder"),
    ("Check live exchange rate and convert between more than 150 world currencies.",
     "Check live exchange rate and convert more than 150 world currencies."),
]


CAMERA_REPLACEMENTS = [
    ("Free browser camera checker. Test camera sharpness, resolution, FPS and hardware support in real time. No download needed. E support laptop camera, USB camera and more.",
     "Free page-side camera checker. Test camera sharpness, resolution, FPS and hardware support live. No download needed. E supports laptop camera, USB camera and more."),
    ("Free browser camera checker. Test sharpness, resolution and FPS in real time without downloading anything.",
     "Free page-side camera checker. Test sharpness, resolution and FPS live without downloading anything."),
    ("Free browser camera checker for sharpness, resolution and frame-rate testing.",
     "Free page-side camera checker for sharpness, resolution and frame-rate testing."),
    ("How do I test camera frame rate (FPS)?", "How I go test camera frame rate (FPS)?"),
    ("What types of cameras na supported?", "Which camera types dis app support?"),
    ("How do I test camera resolution?", "How I go test camera resolution?"),
    ("Read di performance data", "Read di live data"),
    ("Preview of di browser camera checker screen", "Preview of di page-side camera checker screen"),
    ("Browser Camera Checker - Sharpness, Resolution &amp; FPS Test | StarryRing", "Page-side Camera Checker - Sharpness, Resolution &amp; FPS Test | StarryRing"),
    ("Preview of di browser camera checker screen", "Preview of di page-side camera checker screen"),
    ("StarryRing Tool area", "StarryRing tool area"),
    ("Browser Camera Checker", "Page-side Camera Checker"),
    ("Browser camera checker wey dey test sharpness, resolution, frame rate and device health.",
     "Page-side camera checker wey dey test sharpness, resolution, frame rate and device health."),
    ("Dis may be due to browser permission restrictions or camera hardware issues. Make sure say: 1) you allow browser use di camera; 2) camera connect well; 3) no other app dey use am now.",
     "Dis fit happen because permission never show or camera hardware get wahala. Make sure say: 1) you allow the page use your camera; 2) camera connect well; 3) no other app dey use am now."),
    ("How to use di browser camera checker", "How to use di page-side camera checker"),
]


MIC_REPLACEMENTS = [
    ("Free browser microphone checker. Test mic volume, waveform, frequency, noise and delay in real time for USB, Bluetooth and built-in microphones.",
     "Free page-side microphone checker. Test mic volume, waveform, frequency, noise and delay live for USB, Bluetooth and built-in microphones."),
    ("Free browser microphone checker. Test volume, noise and delay with live waveform and spectrum analysis.",
     "Free page-side microphone checker. Test volume, noise and delay with live waveform and spectrum analysis."),
    ("microphone checker, browser mic test, microphone volume test, noise test, audio delay test, USB mic test, Bluetooth mic test",
     "microphone checker, page mic test, microphone volume test, noise test, audio delay test, USB mic test, Bluetooth mic test"),
    ("How to identify microphone issues?", "How I go know microphone get problem?"),
    ("How to test microphone latency?", "How I go test microphone delay?"),
    ("Page-side microphone checker for live volume, waveform, frequency and noise testing.",
     "Page-side microphone checker for live volume, waveform, frequency and noise testing."),
    ("Browser Microphone Checker - Volume, Noise &amp; Delay Test | StarryRing", "Page-side Microphone Checker - Volume, Noise &amp; Delay Test | StarryRing"),
    ("Preview of di browser microphone checker screen", "Preview of di page-side microphone checker screen"),
    ("StarryRing Tool area", "StarryRing tool area"),
    ("Browser Microphone Checker", "Page-side Microphone Checker"),
    ("Browser microphone checker for live volume, waveform, frequency and noise testing.",
     "Page-side microphone checker for live volume, waveform, frequency and noise testing."),
    ("Dis may be due to browser permissions, system settings, or hardware issues. Make sure say: 1) you allow browser use di microphone; 2) correct input device dey your system settings; 3) microphone connect well.",
     "Dis fit happen because permission, system setting or hardware get wahala. Make sure say: 1) you allow the page use the microphone; 2) correct input device dey your system settings; 3) microphone connect well."),
    ("How to use di browser microphone checker", "How to use di page-side microphone checker"),
    ("When prompted, allow di browser to access your microphone. Dis na required for di test to work properly.",
     "When e ask, allow the page use your microphone. Dis na required if the test go work well."),
]


DEAD_PIXEL_REPLACEMENTS = [
    ("Screen Dead pixel test Tool Browser - No-pay Monitor Display Quality Detection | StarryRing",
     "Page-side Screen Dead Pixel Test - Free Monitor Quality Detection | StarryRing"),
    ("Browser screen dead pixel test tool interface preview", "Preview of di page-side screen dead pixel test"),
    ("StarryRing Tool area", "StarryRing tool area"),
    ("Browser Screen Dead Pixel Detection Tool", "Page-side Screen Dead Pixel Detection Tool"),
    ("Pro page-side screen testing tool for dead pixel detection, bright spot check, backlight bleeding analysis, and color uniformity test",
     "Pro page-side screen testing app for dead pixel detection, bright spot check, backlight bleeding reading and color uniformity test"),
    ("How to Use di Screen Dead pixel test Tool", "How to use di screen dead pixel test"),
    ("Click Start Test button", "Start the test"),
    ("Click di 'Start Full Screen check' button to begin di screen dead pixel detection process.",
     "Click 'Start Full Screen check' to begin di screen dead pixel detection process."),
    ("Screen dead pixel checker for browser", "Page-side screen dead pixel checker"),
    ("No-pay tool wey you fit use page-side screen dead pixel detection tool for monitor display quality testing",
     "Free page-side screen dead pixel detection app for monitor display quality testing"),
]


RSA_AES_REPLACEMENTS = [
    ("RSA encrypt app", "RSA lock app"),
    ("RSA decrypt app", "RSA unlock app"),
    ("AES encrypt app", "AES lock app"),
    ("AES decrypt app", "AES unlock app"),
    ("PAGE-SIDE ONLY", "PAGE SIDE ONLY"),
    ("Go to encrypt tool", "Go lock side"),
    ("Need encryption?", "Need lock side?"),
    ("Need decryption?", "Need unlock side?"),
    ("Generate RSA key pair, import PEM public key, and run RSA-OAEP encryption locally inside your page.",
     "Generate RSA key pair, import PEM public key and run RSA-OAEP locking locally inside your page."),
    ("Import PEM private key, decrypt Base64, Hex, or .enc ciphertext, and keep every step inside your page.",
     "Import PEM private key, unlock Base64, Hex or .enc ciphertext, and keep every step inside your page."),
    ("Generate AES key and IV, encrypt text or file with CBC, CTR, or GCM, and keep every step inside your page.",
     "Generate AES key and IV, lock text or file with CBC, CTR or GCM, and keep every step inside your page."),
    ("Import AES key and IV, decrypt Base64, Hex, or .enc ciphertext, and keep every step inside your page.",
     "Import AES key and IV, unlock Base64, Hex or .enc ciphertext, and keep every step inside your page."),
    ("Useful tools", "Useful tools"),
    ("RSA encrypt app", "RSA lock app"),
    ("RSA decrypt app", "RSA unlock app"),
    ("AES encrypt app", "AES lock app"),
    ("AES decrypt app", "AES unlock app"),
    ("RSA encrypt tool", "RSA encrypt app"),
    ("RSA decrypt tool", "RSA decrypt app"),
    ("AES encrypt tool", "AES encrypt app"),
    ("AES decrypt tool", "AES decrypt app"),
    ("BROWSER ONLY", "PAGE-SIDE ONLY"),
    ("PAGE-SIDE ONLY", "PAGE SIDE ONLY"),
    ("Client-side only", "Page-side only"),
    ("browser-side", "page-side"),
    ("browser-only", "page-side only"),
    ("browser", "page"),
    ("Go to encrypt tool", "Go lock side"),
    ("Need encryption?", "Need lock side?"),
    ("Need decryption?", "Need unlock side?"),
    ("GENERATE KEY PAIR", "MAKE KEY PAIR"),
    ("GENERATE</button>", "MAKE KEY</button>"),
    ("Generate AES key and IV, encrypt text or file with CBC, CTR, or GCM, and keep every step inside your page.",
     "Generate AES key and IV, lock text or file with CBC, CTR or GCM, and keep every step inside your page."),
    ("Import AES key and IV, decrypt Base64, Hex, or .enc ciphertext, and keep every step inside your page.",
     "Import AES key and IV, unlock Base64, Hex or .enc ciphertext, and keep every step inside your page."),
    ("Import PEM private key, decrypt Base64, Hex, or .enc ciphertext, and keep every step inside your page.",
     "Import PEM private key, unlock Base64, Hex or .enc ciphertext, and keep every step inside your page."),
    ("Generate RSA key pair, import PEM public key, and run RSA-OAEP encryption locally inside your page.",
     "Generate RSA key pair, import PEM public key and run RSA-OAEP locking locally inside your page."),
]


VIDEO_CONVERTER_REPLACEMENTS = [
    ("video-converter app/", "video-converter/"),
    ("video-converter app\"", "video-converter\""),
    ("video-converter app'", "video-converter'"),
    ("VIDFORM &mdash; Video converter app for browser", "VIDFORM &mdash; Page-side video converter"),
    ("VIDFORM na page-side video converter app wey fit handle plenty formats with local FFmpeg processing.",
     "VIDFORM na page-side video converter wey fit handle plenty formats with local FFmpeg processing."),
    ("VIDFORM na browser video converter wey fit handle plenty formats with local FFmpeg processing.",
     "VIDFORM na page-side video converter wey fit handle plenty formats with local FFmpeg processing."),
    ("Video converter app", "Video converter"),
    ("video converter app", "video converter"),
    ("Video converter for browser", "Page-side video converter"),
    ("video converter for browser", "page-side video converter"),
    ("browser video converter", "page-side video converter"),
    ("Browser video converter", "Page-side video converter"),
    ("local work for browser", "local page-side work"),
]


AUDIO_CONVERTER_REPLACEMENTS = [
    ("Page-side audio converter app - free MP3/WAV/FLAC/AAC tool | StarryRing", "Page-side audio converter - free MP3/WAV/FLAC/AAC tool | StarryRing"),
    ("Page-side audio converter app", "Page-side audio converter"),
    ("audio converter app", "audio converter"),
    ("Audio converter app", "Audio converter"),
    ("page-side audio converter app", "page-side audio converter"),
]


VOICE_RECORDER_REPLACEMENTS = [
    ("Page-side audio recorder app &ndash; record system sound or microphone | Audio Studio", "Page-side audio recorder &ndash; record system sound or microphone | Audio Studio"),
    ("Page-side audio recorder app", "Page-side audio recorder"),
    ("audio recorder app", "audio recorder"),
    ("Audio recorder app", "Audio recorder"),
    ("Free browser recorder wey fit capture system sound or microphone, no installation. E support scheduled stop, WEBM/WAV export and live waveform.",
     "Free page-side recorder wey fit capture system sound or microphone, no installation. E supports scheduled stop, WEBM/WAV export and live waveform."),
    ("Free browser audio recorder. Record system sound or microphone, set scheduled stop, and export WEBM or WAV. Chrome and Edge work best; macOS fit need BlackHole.",
     "Free page-side audio recorder. Record system sound or microphone, set scheduled stop, and export WEBM or WAV. Chrome and Edge work best; macOS fit need BlackHole."),
    ("Audio recorder for browser – system sound or microphone", "Page-side audio recorder – system sound or microphone"),
    ("Audio recorder for browser", "Page-side audio recorder"),
    ("browser share dialog", "page share dialog"),
]


COLOR_GRADING_REPLACEMENTS = [
    ("browser color grading", "page-side color grading"),
    ("Browser color grading", "Page-side color grading"),
    ("browser color tool", "page-side color tool"),
    ("Browser color tool", "Page-side color tool"),
]


IMAGE_CONVERTER_EXTRA_REPLACEMENTS = [
    ("Image resize and convert app - private page-side studio app | StarryRing", "Image resize and convert page - private page-side studio | StarryRing"),
    ("Private page-side image studio app", "Private page-side image studio"),
    ("private page-side image studio app", "private page-side image studio"),
    ("Private image studio app main screen", "Private image studio main screen"),
    ("Wetin be dis private image studio app?", "Wetin be dis private image studio?"),
    ("How to resize and convert image with dis private page-side studio app", "How to resize and convert image with dis private page-side studio"),
    ("Image resize and convert tool - private page-side studio app", "Image resize and convert page - private page-side studio"),
    ("Tool to resize and convert image", "Image resize and convert page"),
    ("Private page-side image studio app - resize and convert image", "Private page-side image studio - resize and convert image"),
    ("Wetin dis private page-side image studio app fit do", "Wetin dis private page-side image studio fit do"),
    ("Image resize and convert tool", "Image resize and convert page"),
]


FILE_REPLACEMENTS = {
    ROOT / "pcm" / "utility-tools" / "netdev" / "post-tool" / "index.html": POST_REPLACEMENTS,
    ROOT / "pcm" / "utility-tools" / "netdev" / "websocket-test" / "index.html": WEBSOCKET_REPLACEMENTS,
    ROOT / "pcm" / "toolbox" / "keyboard" / "index.html": KEYBOARD_REPLACEMENTS,
    ROOT / "pcm" / "utility-tools" / "math" / "password-generator" / "index.html": PASSWORD_REPLACEMENTS,
    ROOT / "pcm" / "toolbox" / "index.html": TOOLBOX_INDEX_REPLACEMENTS,
    ROOT / "pcm" / "utility-tools" / "math" / "random-number-generator" / "index.html": RANDOM_NUMBER_REPLACEMENTS,
    ROOT / "pcm" / "toolbox" / "speaker" / "index.html": SPEAKER_REPLACEMENTS,
    ROOT / "pcm" / "utility-tools" / "netdev" / "ping" / "index.html": PING_REPLACEMENTS,
    ROOT / "pcm" / "utility-tools" / "design-media" / "app-icon-generator" / "index.html": APP_ICON_REPLACEMENTS,
    ROOT / "pcm" / "utility-tools" / "design-media" / "image-converter" / "index.html": IMAGE_CONVERTER_REPLACEMENTS + IMAGE_CONVERTER_EXTRA_REPLACEMENTS,
    ROOT / "pcm" / "utility-tools" / "design-media" / "video-converter" / "index.html": VIDEO_CONVERTER_REPLACEMENTS,
    ROOT / "pcm" / "utility-tools" / "design-media" / "audio-converter" / "index.html": AUDIO_CONVERTER_REPLACEMENTS,
    ROOT / "pcm" / "utility-tools" / "design-media" / "online-voice-recorder" / "index.html": VOICE_RECORDER_REPLACEMENTS,
    ROOT / "pcm" / "utility-tools" / "design-media" / "color-grading" / "index.html": COLOR_GRADING_REPLACEMENTS,
    ROOT / "pcm" / "utility-tools" / "design-media" / "favicon-generator" / "index.html": FAVICON_REPLACEMENTS,
    ROOT / "pcm" / "utility-tools" / "index.html": UTILITY_INDEX_REPLACEMENTS,
    ROOT / "pcm" / "toolbox" / "camera" / "index.html": CAMERA_REPLACEMENTS,
    ROOT / "pcm" / "toolbox" / "camera" / "index.html": CAMERA_REPLACEMENTS + CAMERA_EXTRA_REPLACEMENTS,
    ROOT / "pcm" / "toolbox" / "mic" / "index.html": MIC_REPLACEMENTS,
    ROOT / "pcm" / "toolbox" / "mic" / "index.html": MIC_REPLACEMENTS + MIC_EXTRA_REPLACEMENTS,
    ROOT / "pcm" / "toolbox" / "dead-pixel" / "index.html": DEAD_PIXEL_REPLACEMENTS,
    ROOT / "pcm" / "utility-tools" / "math" / "rsa-encrypt" / "index.html": RSA_AES_REPLACEMENTS,
    ROOT / "pcm" / "utility-tools" / "math" / "rsa-decrypt" / "index.html": RSA_AES_REPLACEMENTS,
    ROOT / "pcm" / "utility-tools" / "math" / "aes-encrypt" / "index.html": RSA_AES_REPLACEMENTS,
    ROOT / "pcm" / "utility-tools" / "math" / "aes-decrypt" / "index.html": RSA_AES_REPLACEMENTS,
    ROOT / "pcm" / "toolbox" / "mouse" / "instruction" / "index.html": MOUSE_INSTRUCTION_REPLACEMENTS,
    ROOT / "pcm" / "toolbox" / "mouse" / "double-click" / "instruction" / "index.html": DOUBLE_CLICK_INSTRUCTION_REPLACEMENTS,
}


def main():
    changed = []
    for path, replacements in FILE_REPLACEMENTS.items():
        if replace_many(path, replacements):
            changed.append(path.relative_to(ROOT).as_posix())
    for item in changed:
        print(item)


if __name__ == "__main__":
    main()
