from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def replace_all(path_str, replacements):
    path = ROOT / path_str
    text = path.read_text(encoding="utf-8")
    original = text
    for old, new in replacements:
        text = text.replace(old, new)
    if text != original:
        path.write_text(text, encoding="utf-8")
        return True
    return False


IMAGE_HTML_REPLACEMENTS = [
    ("<title>Image Resizer &amp; Converter - Privacy Image Studio | No-pay tool wey you fit use for internet</title>",
     "<title>Image resize and convert tool - Privacy Image Studio | Free browser tool</title>"),
    ('<meta content="Privacy Image Studio screenshot - free for internet image resizer and converter" property="og:image:alt"/>',
     '<meta content="Privacy Image Studio screenshot - browser tool wey fit resize and convert image" property="og:image:alt"/>'),
    ('"name": "Privacy Image Studio - Image Resizer & Converter",',
     '"name": "Privacy Image Studio - Tool to resize and convert image",'),
    ('"description": "No-pay tool wey you fit use for internet image resizer and converter. Adjust image size, dimensions, aspect ratio, resolution. Convert PNG, JPG, WebP, HEIC, TIFF, BMP, SVG. 100% local processing, no upload, privacy safe.",',
     '"description": "Free browser tool wey fit resize and convert image. Change image size, width, height, ratio and format like PNG, JPG, WebP, HEIC, TIFF, BMP and SVG. Everything dey run for your browser, no upload.",'),
    ('"caption": "Privacy Image Studio interface"',
     '"caption": "Privacy Image Studio main screen"'),
    ('"caption": "Image resizing interface",',
     '"caption": "Image resize screen",'),
    ('"description": "Upload images, choose resize mode, select output format, batch process"',
     '"description": "Upload image, choose resize mode, pick output format and process many files together"'),
    ('"featureList": [',
     '"featureList": ['),
    ('"100% local processing (no upload)",',
     '"Everything dey run for your browser, no upload",'),
    ('"Resize images: scale by percent, set width/height, free stretch",',
     '"Resize image by percent, fixed width, fixed height or free stretch",'),
    ('"Adjust dimensions, aspect ratio, resolution",',
     '"Change size, ratio and resolution",'),
    ('"Batch processing",',
     '"Process plenty images together",'),
    ('"Real-time preview and size comparison",',
     '"Quick preview and size comparison",'),
    ('"Download as ZIP",',
     '"Download as ZIP file",'),
    ('"Privacy safe: all processing in browser"',
     '"Private use: everything dey run inside browser"'),
    ('<meta content="No-pay tool wey you fit use for internet image resizer and converter. Adjust image size, dimensions, aspect ratio, resolution. Convert PNG, JPG, WebP, HEIC, TIFF, BMP, SVG. 100% local processing, no upload, privacy safe." name="description"/>',
     '<meta content="Free browser tool wey fit resize and convert image. Change width, height, ratio and format like PNG, JPG, WebP, HEIC, TIFF, BMP and SVG. Everything dey run locally, no upload." name="description"/>'),
    ('<meta content="Image Resizer &amp; Converter - Privacy Image Studio | No-pay tool wey you fit use for internet" property="og:title"/>',
     '<meta content="Image resize and convert tool - Privacy Image Studio" property="og:title"/>'),
    ('<meta content="No-pay tool wey you fit use for internet tool to resize images and convert formats. Adjust size, dimensions, aspect ratio. Convert PNG, JPG, WebP, HEIC, TIFF, BMP, SVG. 100% local, no upload." property="og:description"/>',
     '<meta content="Resize image and change format for browser. Change size, ratio and output format without upload." property="og:description"/>'),
    ('<meta content="Image Resizer &amp; Converter - Privacy Image Studio" name="twitter:title"/>',
     '<meta content="Image resize and convert tool - Privacy Image Studio" name="twitter:title"/>'),
    ('<meta content="No-pay tool wey you fit use for internet image resizer and converter. Adjust size, dimensions, aspect ratio. Convert HEIC, SVG, WebP, PNG, JPG. 100% local, private." name="twitter:description"/>',
     '<meta content="Resize image and convert format for browser. Support HEIC, SVG, WebP, PNG and JPG. Local and private." name="twitter:description"/>'),
    ('<meta content="image resizer, resize image for internet, image size adjust, image converter, change image dimensions, image aspect ratio, HEIC to JPG, SVG to PNG, WebP converter, image compression, privacy safe" name="keywords"/>',
     '<meta content="image resize tool, image converter, change image size, HEIC to JPG, SVG to PNG, WebP converter, private browser tool" name="keywords"/>'),
    ('<a class="breadcrumb-link" href="/pcm/utility-tools/">\n<i class="fas fa-toolbox"></i>Utility tools</a>',
     '<a class="breadcrumb-link" href="/pcm/utility-tools/">\n<i class="fas fa-toolbox"></i>Useful tools</a>'),
    ('<span class="breadcrumb-active"><i class="fas fa-exchange-alt"></i>Image Resizer &amp; Converter</span>',
     '<span class="breadcrumb-active"><i class="fas fa-exchange-alt"></i>Tool to resize and convert image</span>'),
    ('<h1>Privacy Image Studio - Image Resizer &amp; Converter</h1>',
     '<h1>Privacy Image Studio - Tool to resize and convert image</h1>'),
    ('<p class="subtitle">100% local processing &middot; resize images &middot; adjust dimensions &middot; convert formats &middot; privacy safe</p>',
     '<p class="subtitle">Everything dey run for your browser &middot; resize image &middot; change size &middot; switch format &middot; private use</p>'),
    ('<b>Add images to start</b>',
     '<b>Add image make we start</b>'),
    ('<span>Resize and convert PNG, JPG, WebP, HEIC, TIFF, BMP, SVG (100% local, no upload)</span>',
     '<span>Resize and convert PNG, JPG, WebP, HEIC, TIFF, BMP, SVG (na local work, no upload)</span>'),
    ('<div class="hint"><i class="fas fa-info-circle"></i>Drag &amp; drop files or click to select</div>',
     '<div class="hint"><i class="fas fa-info-circle"></i>Drag and drop file or click make you choose am</div>'),
    ('<thead><tr><th>Preview</th><th>Filename</th><th>Size change (px)</th><th>Status</th><th style="text-align:right">Action</th></tr></thead>',
     '<thead><tr><th>Preview</th><th>File name</th><th>Size change (px)</th><th>Status</th><th style="text-align:right">Action</th></tr></thead>'),
    ('<label><i class="fas fa-expand-alt"></i>Resize Mode</label>',
     '<label><i class="fas fa-expand-alt"></i>How you wan resize am</label>'),
    ('<option value="percent">Scale by percent</option>',
     '<option value="percent">Scale by percent</option>'),
    ('<option value="width">Fixed width (maintain ratio)</option>',
     '<option value="width">Fixed width (keep ratio)</option>'),
    ('<option value="height">Fixed height (maintain ratio)</option>',
     '<option value="height">Fixed height (keep ratio)</option>'),
    ('<option value="free">No-pay stretch</option>',
     '<option value="free">Free stretch</option>'),
    ('<div class="control-tip">Choose how to adjust image dimensions</div>',
     '<div class="control-tip">Choose how you wan change image size</div>'),
    ('<div class="control-tip">Percentage of original size (100% = original)</div>',
     '<div class="control-tip">Percent of the original size (100% na original)</div>'),
    ('<label><i class="fas fa-arrows-alt-h"></i>Width (px)</label>',
     '<label><i class="fas fa-arrows-alt-h"></i>Width (px)</label>'),
    ('<div class="control-tip">Set width, height auto‑scaled to maintain aspect ratio</div>',
     '<div class="control-tip">Set width, make height balance by itself keep ratio</div>'),
    ('<label><i class="fas fa-arrows-alt-v"></i>Height (px)</label>',
     '<label><i class="fas fa-arrows-alt-v"></i>Height (px)</label>'),
    ('<div class="control-tip">Set height, width auto‑scaled to maintain aspect ratio</div>',
     '<div class="control-tip">Set height, make width balance by itself keep ratio</div>'),
    ('<label><i class="fas fa-expand"></i>Dimensions (W&times;H)</label>',
     '<label><i class="fas fa-expand"></i>Size (W&times;H)</label>'),
    ('placeholder="Width"', 'placeholder="Width"'),
    ('placeholder="Height"', 'placeholder="Height"'),
    ('<div class="control-tip">Set both width and height (may stretch image)</div>',
     '<div class="control-tip">Set width and height together (e fit stretch image)</div>'),
    ('<label><i class="fas fa-file-export"></i>Output Format</label>',
     '<label><i class="fas fa-file-export"></i>Output format</label>'),
    ('<div class="control-tip">PNG: lossless, supports transparency<br/>JPEG: lossy, small file<br/>WebP: high compression<br/>BMP: uncompressed, highest quality<br/>TIFF: industry standard for print</div>',
     '<div class="control-tip">PNG: clear, support transparent background<br/>JPEG: smaller file<br/>WebP: strong compression<br/>BMP: no compression, big quality<br/>TIFF: standard for print work</div>'),
    ('<div id="hint-text"><i class="fas fa-exclamation-triangle"></i>Settings changed, please reprocess</div>',
     '<div id="hint-text"><i class="fas fa-exclamation-triangle"></i>Setting don change, run am again</div>'),
    ('<button class="btn-main" disabled="" id="btn-run"><i class="fas fa-bolt"></i>Process</button>',
     '<button class="btn-main" disabled="" id="btn-run"><i class="fas fa-bolt"></i>Run am</button>'),
    ('<button class="btn-main" id="btn-download-main">Download</button>',
     '<button class="btn-main" id="btn-download-main">Download</button>'),
    ('<div id="modal-tag"><i class="fas fa-search"></i>Preview</div>',
     '<div id="modal-tag"><i class="fas fa-search"></i>Preview</div>'),
    ('<p><i class="fas fa-lock"></i>All image processing (resize, convert) na done locally in your browser &ndash; no upload |<i class="fas fa-code"></i>Pure front‑end technology</p>',
     '<p><i class="fas fa-lock"></i>All image work (resize, convert) dey happen for your browser &ndash; no upload |<i class="fas fa-code"></i>Pure front-end tech</p>'),
    ('<h2>Privacy Image Studio Wetin e fit do: Resize &amp; Convert</h2>',
     '<h2>Wetin Privacy Image Studio fit do: resize and convert image</h2>'),
    ('<p>📖 Pro local image resizer and converter supporting multiple formats and intelligent dimension adjustments. Integrates<strong>image resizer</strong>, <strong>image converter</strong>, <strong>HEIC converter</strong>, <strong>SVG converter</strong>, and<strong>local image processing</strong>in one tool.</p>',
     '<p>📖 Dis na browser tool wey fit resize image, convert format, handle HEIC and SVG, and change image size without upload.</p>'),
    ('<h3><i class="fas fa-lock"></i>100% Privacy Safe</h3>',
     '<h3><i class="fas fa-lock"></i>100% private use</h3>'),
    ('<p>All image resizing and conversion happens locally in your browser. Your images never leave your device, ensuring complete privacy.</p>',
     '<p>All image resizing and conversion dey happen for your browser. Your files no leave your device at all.</p>'),
    ('<span class="tip-text">No upload &ndash; ideal for sensitive or private images</span>',
     '<span class="tip-text">No upload &ndash; e good for private or sensitive image</span>'),
    ('<h3><i class="fas fa-exchange-alt"></i>Full Format Support</h3>',
     '<h3><i class="fas fa-exchange-alt"></i>Plenty format support</h3>'),
    ('<p>E support PNG, JPEG, WebP, BMP, TIFF, HEIC/HEIF, and SVG. Convert iPhone HEIC photos or SVG vector graphics, and resize them at di same time.</p>',
     '<p>E support PNG, JPEG, WebP, BMP, TIFF, HEIC/HEIF and SVG. You fit convert iPhone HEIC photo or SVG graphic and resize am together.</p>'),
    ('<h3><i class="fas fa-vector-square"></i>SVG Vector Support</h3>',
     '<h3><i class="fas fa-vector-square"></i>SVG support</h3>'),
    ('<p>Convert SVG to raster formats (PNG, JPEG, etc.) with custom output dimensions. Perfect for generating high‑quality icons and logos at any size.</p>',
     '<p>Convert SVG to PNG, JPEG and other raster formats with the exact size wey you want. E good for icon and logo work.</p>'),
    ('<h3><i class="fas fa-expand-alt"></i>Smart Resizing</h3>',
     '<h3><i class="fas fa-expand-alt"></i>Smart resize</h3>'),
    ('<p>Multiple resize modes: scale by percent, fixed width/height (maintain ratio), free stretch. Easily adjust image dimensions, aspect ratio, and resolution.</p>',
     '<p>You get many resize modes: percent, fixed width, fixed height and free stretch. E easy to change size, ratio and resolution.</p>'),
    ('<h3><i class="fas fa-layer-group"></i>Batch Processing</h3>',
     '<h3><i class="fas fa-layer-group"></i>Batch processing</h3>'),
    ('<p>Upload multiple images at once. Resize and convert them in batch, then download all as a ZIP archive.</p>',
     '<p>Upload many images once, run resize and convert together, then download all of them as ZIP.</p>'),
    ('<h3><i class="fas fa-eye"></i>Live Preview</h3>',
     '<h3><i class="fas fa-eye"></i>Live preview</h3>'),
    ('<p>See original vs. resized dimensions in real time. Preview images to confirm results before downloading.</p>',
     '<p>See original size and new size straight away. Preview image before you download am.</p>'),
    ('<h2>Technical details</h2>',
     '<h2>Technical details</h2>'),
    ('<p>Formats and technologies used:</p>',
     '<p>Formats and tech wey dis tool dey use:</p>'),
    ('<p class="tech-note"><strong>Note:</strong>All processing uses Web Workers to keep di interface responsive. For very large images, processing may take a few seconds but won\'t freeze di page.</p>',
     '<p class="tech-note"><strong>Note:</strong>Dis tool dey use Web Workers so the page no go hang. Very big image fit take small time, but e no go freeze the page.</p>'),
    ('<h3>Why use a local image resizer?</h3>',
     '<h3>Why e good make you use local image resizer?</h3>'),
    ('<p>Traditional for internet tools require uploading images to a server, risking privacy. Our tool runs entirely in your browser &mdash; your images stay on your device. Perfect for personal, confidential, or sensitive images.</p>',
     '<p>Many web tools need upload to server, and dat one fit spoil privacy. Our own dey run for your browser, so your image stay with you for device.</p>'),
    ('<p>Yes! Select a resize mode (percent, fixed width, fixed height, or free stretch), enter di desired values, and click "Process". Di tool go generate resized images locally.</p>',
     '<p>Yes. Choose resize mode, enter the size wey you want, then click "Run am". The tool go produce the resized image for your browser.</p>'),
    ('<p>HEIC na di default photo format on iPhones/iPads. It offers better compression than JPEG but na not universally supported. Our tool converts HEIC to JPG/PNG so you fit view and use them anywhere.</p>',
     '<p>HEIC na the default photo format for iPhone and iPad. E compress well pass JPEG but no dey open everywhere. Our tool fit turn am to JPG or PNG.</p>'),
    ('<p>Absolutely. Upload SVG files and choose an output raster format (PNG, JPEG, WebP, BMP, TIFF). You fit also set di output dimensions to get exactly di size you need.</p>',
     '<p>Yes. Upload SVG, choose output like PNG, JPEG, WebP, BMP or TIFF, and set the exact size wey you need.</p>'),
    ('<p>Yes, completely free. No registration, no hidden fees. Just resize and convert your images privately.</p>',
     '<p>Yes, e totally free. No registration, no hidden fee. Just resize and convert your image privately.</p>'),
    ('<p>All modern browsers: Chrome 65+, Firefox 61+, Safari 11.1+, Edge 79+. Mobile browsers (iOS Safari, Android Chrome) work too.</p>',
     '<p>Modern browsers like Chrome, Firefox, Safari and Edge fit run am. Mobile browser too fit work.</p>'),
    ('<p>&copy; 2024 StarryRing - Privacy Image Studio (Image Resizer &amp; Converter)</p>',
     '<p>&copy; 2024 StarryRing - Privacy Image Studio (image resize and convert tool)</p>'),
    ('<p>Last updated: February 2026 | Version: v1.4.0 | Technology: HTML5 Canvas + Web Workers + SVG support</p>',
     '<p>Last update: February 2026 | Version: v1.4.0 | Tech: HTML5 Canvas + Web Workers + SVG support</p>'),
]


IMAGE_JS_REPLACEMENTS = [
    ("Local Processing · Size Comparison Preview · Full Format Support", "Local work · Compare size quick · Plenty format support"),
    ("<i class=\"fas fa-sync-alt\"></i> Reprocess", "<i class=\"fas fa-sync-alt\"></i> Run am again"),
    ("Needs Update", "Need update"),
    ("<i class=\"fas fa-bolt\"></i> Start Processing", "<i class=\"fas fa-bolt\"></i> Start work"),
    ("<i class=\"fas fa-spinner fa-spin\"></i> Loading", "<i class=\"fas fa-spinner fa-spin\"></i> Dey load"),
    ("<i class=\"fas fa-clock\"></i> Waiting", "<i class=\"fas fa-clock\"></i> Dey wait"),
    ("<i class=\"fas fa-eye\"></i> Original", "<i class=\"fas fa-eye\"></i> Original"),
    ("<i class=\"fas fa-magic\"></i> Result", "<i class=\"fas fa-magic\"></i> Result"),
    ("Original Image Preview", "Preview of original image"),
    ("Read Failed", "Read fail"),
    ("SVG loading failed", "SVG no gree load"),
    ("<i class=\"fas fa-spinner fa-spin\"></i> Processing...", "<i class=\"fas fa-spinner fa-spin\"></i> Dey process..."),
    ("<i class=\"fas fa-cog fa-spin\"></i> Processing", "<i class=\"fas fa-cog fa-spin\"></i> Dey process"),
    ("<i class=\"fas fa-check-circle\"></i> Ready", "<i class=\"fas fa-check-circle\"></i> Ready"),
    ("Processed Result Preview", "Preview of result"),
    ("<i class=\"fas fa-download\"></i> Save to Computer", "<i class=\"fas fa-download\"></i> Save am for computer"),
    ("<i class=\"fas fa-file-archive\"></i> Download All (${fileQueue.length} images)", "<i class=\"fas fa-file-archive\"></i> Download all (${fileQueue.length} images)"),
    ("<i class=\"fas fa-spinner fa-spin\"></i> Packaging...", "<i class=\"fas fa-spinner fa-spin\"></i> Dey package..."),
    ("Privacy_Studio_Export_", "privacy_studio_export_"),
    ("_converted.", "_don_convert."),
    ("<i class=\"fas fa-times-circle\"></i> Failed", "<i class=\"fas fa-times-circle\"></i> Fail"),
]


AUDIO_HTML_REPLACEMENTS = [
    ("<title>For internet Audio Format Converter - No-pay MP3/WAV/FLAC/AAC Conversion | WAVFORM</title>",
     "<title>Audio converter for browser - free MP3/WAV/FLAC/AAC tool | WAVFORM</title>"),
    ('"description": "No-pay tool wey you fit use for internet audio converter tool. Convert between MP3, WAV, FLAC, AAC, OGG, AIFF and more, or extract audio tracks from video files. All processing happens locally in your browser – no upload, privacy safe.",',
     '"description": "Free browser audio converter. Convert MP3, WAV, FLAC, AAC, OGG and AIFF, or pull audio from video files. Everything dey run locally, no upload.",'),
    ('<meta content="No-pay tool wey you fit use for internet audio converter tool. Convert between MP3, WAV, FLAC, AAC, OGG, AIFF and more, or extract audio tracks from MP4/MKV/MOV videos. All processing happens locally in your browser &ndash; no upload, privacy safe." name="description"/>',
     '<meta content="Free browser audio converter. Convert MP3, WAV, FLAC, AAC, OGG and AIFF, or pull audio from MP4, MKV and MOV video. Everything dey run locally, no upload." name="description"/>'),
    ('<meta content="For internet Audio Format Converter - No-pay Local Processing" property="og:title"/>',
     '<meta content="Audio converter for browser - free local processing" property="og:title"/>'),
    ('<meta content="Convert between MP3, WAV, FLAC, AAC and more, extract audio from videos. No upload, privacy safe." property="og:description"/>',
     '<meta content="Convert MP3, WAV, FLAC, AAC and more, or pull audio from video. No upload, private use." property="og:description"/>'),
    ('<meta content="For internet Audio Format Converter - No-pay Local Processing" name="twitter:title"/>',
     '<meta content="Audio converter for browser - free local processing" name="twitter:title"/>'),
    ('<meta content="audio converter, for internet converter, MP3 converter, WAV converter, FLAC converter, video to audio, free, local processing" name="keywords"/>',
     '<meta content="audio converter, MP3 converter, WAV converter, FLAC converter, video to audio, free browser tool" name="keywords"/>'),
    ('<i class="fas fa-toolbox"></i>Utilities</a>',
     '<i class="fas fa-toolbox"></i>Useful tools</a>'),
    ('<span class="breadcrumb-active">Audio converter</span>',
     '<span class="breadcrumb-active">Audio converter</span>'),
    ('<div class="logo-sub">Audio Format Converter</div>',
     '<div class="logo-sub">Audio converter</div>'),
    ('<div class="badge-dot"></div>Local Processing &middot; Privacy Safe</div>',
     '<div class="badge-dot"></div>Local work &middot; Private use</div>'),
    ('<h1 class="page-main-title">For internet Audio Format Converter<span class="title-badge">No-pay &middot; Local</span>',
     '<h1 class="page-main-title">Audio converter for browser<span class="title-badge">Free &middot; Local</span>'),
    ('<div class="section-label">01 &mdash; Upload Files</div>',
     '<div class="section-label">01 &mdash; Upload files</div>'),
    ('<div class="drop-title">Drag &amp; drop audio files here</div>',
     '<div class="drop-title">Drag and drop audio file here</div>'),
    ('<div class="drop-subtitle">or click to select &middot; E support all audio formats and video-to-audio extraction</div>',
     '<div class="drop-subtitle">or click choose am &middot; e support many audio formats and video-to-audio work</div>'),
    ('<button class="clear-all-btn" onclick="clearAll()">Clear All</button>',
     '<button class="clear-all-btn" onclick="clearAll()">Clear all</button>'),
    ('<div class="section-label">03 &mdash; Conversion Settings</div>',
     '<div class="section-label">03 &mdash; Conversion settings</div>'),
    ('<label>Output Format</label>',
     '<label>Output format</label>'),
    ('<label>Sample Rate</label>',
     '<label>Sample rate</label>'),
    ('<label>Channels</label>',
     '<label>Channels</label>'),
    ('<div class="btn-shimmer"></div>⚡ Start Conversion</button>',
     '<div class="btn-shimmer"></div>⚡ Start conversion</button>'),
    ('<div class="section-label">04 &mdash; Download Results</div>',
     '<div class="section-label">04 &mdash; Download results</div>'),
    ('<div class="section-label">&mdash; Conversion Log</div>',
     '<div class="section-label">&mdash; Conversion log</div>'),
    ('<h2>Pro Audio converter Wetin e fit do</h2>',
     '<h2>Wetin this audio converter fit do</h2>'),
    ('<p>Choose from WAV, AIFF lossless formats, or MP3, OGG, WebM lossy formats. Perfect for archiving, sharing, or mobile devices.</p>',
     '<p>Choose WAV and AIFF for lossless work, or MP3, OGG and WebM for smaller file. E good for archive, sharing and phone use.</p>'),
    ('<p>Drag in MP4, MKV, MOV, AVI files and automatically extract di audio stream to your chosen format. No extra tools needed.</p>',
     '<p>Drop MP4, MKV, MOV or AVI file and the tool go pull the audio track into the format wey you choose. No extra tool needed.</p>'),
    ('<p>Customize sample rate (8kHz to 96kHz), channel count (mono/stereo), and bitrate (MP3). Full control over output quality.</p>',
     '<p>Change sample rate, channel count and MP3 bitrate yourself. You get control over output quality.</p>'),
    ('<p>All processing happens inside your browser. Your files never leave your device. Convert sensitive recordings with confidence.</p>',
     '<p>Everything dey happen for your browser. Your file no leave your device, so you fit handle private recording with mind at rest.</p>'),
    ('<p>Select multiple files at once; they queue up and na processed one by one. Download individually or batch‑package later.</p>',
     '<p>You fit choose many files once. Dem go line up, process one by one, and you fit download one by one or together later.</p>'),
    ('<p>Preview converted audio directly on di page before downloading. Saves time and avoids repeated downloads.</p>',
     '<p>You fit preview the converted audio for the page before download. E save time and stop repeat download.</p>'),
    ('<div class="tip">Pause, seek &ndash; quick preview.</div>',
     '<div class="tip">Pause and seek &ndash; quick preview.</div>'),
    ('<p>Yes, 100% local processing. We use di Web Audio API to decode, lamejs to encode MP3, and MediaRecorder for Opus. Everything happens in your browser\'s memory &ndash; no network transfer. You fit even use dis tool offline (after di page has been loaded once).</p>',
     '<p>Yes, na fully local work. The tool decode and encode for your browser memory, no network transfer. After the page load once, you even fit use am offline.</p>'),
    ('<p>Yes. Select several files &ndash; they appear in di queue. Click &ldquo;Start Conversion&rdquo; and di tool processes them one by one. You fit add or remove files during conversion, but files dat na currently being processed cannot be modified.</p>',
     '<p>Yes. Choose many files and dem go show for queue. Click &ldquo;Start conversion&rdquo; and the tool go run them one by one.</p>'),
    ('<span style="color:var(--amber)">🔒</span>All processing done locally in your browser &ndash; files never uploaded to any server</div>',
     '<span style="color:var(--amber)">🔒</span>All processing dey happen for your browser &ndash; file no upload go any server</div>'),
]


AUDIO_JS_REPLACEMENTS = [
    ("(not supported in this browser)", "(dis browser no support am)"),
    ("Lossless PCM format, perfectly preserves original quality. Larger file size, suitable for professional production and archiving.",
     "Lossless PCM format wey keep original quality full. File go bigger, and e good for pro work and archive."),
    ("Apple AIFF format, big-endian PCM, same quality as WAV, ideal for Mac/iOS workflows.",
     "Apple AIFF format, same quality like WAV, good for Mac and iOS workflow."),
    ("OGG/Opus encoded in real-time by the browser. Encoding speed equals audio duration (1× real-time). Longer files may take time.",
     "Browser go encode OGG/Opus in real time. Long file fit take time."),
    ("WebM/Opus encoded in real-time by the browser. Encoding speed equals audio duration (1× real-time). Longer files may take time.",
     "Browser go encode WebM/Opus in real time. Long file fit take time."),
    ("✦ Original (Auto)", "✦ Original (Auto)"),
    ("READY", "READY"),
    ("SCANNING", "SCANNING"),
    ("PROCESSING", "PROCESSING"),
    ("DONE", "DONE"),
    ("ERROR", "ERROR"),
    ("Please upload files first", "Upload file first"),
    ("⏳ Converting...", "⏳ Dey convert..."),
    ("</svg>Download</a>", "</svg>Download</a>"),
    ("Preparing...", "Dey prepare..."),
    ("Decoding", "Dey decode"),
    ("Encoding → ", "Dey encode → "),
    ("Creating blob...", "Dey create file..."),
    ("Engine ready — WAV · AIFF · MP3 · OGG · WebM output · Audio/video input supported",
     "Engine ready — WAV · AIFF · MP3 · OGG · WebM output · audio and video input dey supported"),
    ("Start Conversion", "Start conversion"),
    ("Convert Again", "Convert again"),
]


RECORDER_HTML_REPLACEMENTS = [
    ("<title>For internet Audio Recorder &ndash; Record System Audio or Microphone | Audio Studio</title>",
     "<title>Audio recorder for browser &ndash; record system sound or microphone | Audio Studio</title>"),
    ('"description": "No-pay tool wey you fit use for internet tool to record system audio or microphone, no installation required. E support scheduled stop, export to WEBM/WAV, real‑time waveform.",',
     '"description": "Free browser recorder wey fit capture system sound or microphone, no installation. E support scheduled stop, WEBM/WAV export and live waveform.",'),
    ('<meta content="No-pay tool wey you fit use for internet audio recorder. No software installation needed. Record system audio or microphone. Scheduled stop, export to WEBM/WAV, real‑time waveform. Works in Chrome/Edge, macOS may need BlackHole." name="description"/>',
     '<meta content="Free browser audio recorder. Record system sound or microphone, set scheduled stop, and export WEBM or WAV. Chrome and Edge work best; macOS fit need BlackHole." name="description"/>'),
    ('<meta content="For internet Audio Recorder &ndash; System Audio or Microphone" property="og:title"/>',
     '<meta content="Audio recorder for browser &ndash; system sound or microphone" property="og:title"/>'),
    ('<meta content="For internet Audio Recorder &ndash; System Audio or Microphone" name="twitter:title"/>',
     '<meta content="Audio recorder for browser &ndash; system sound or microphone" name="twitter:title"/>'),
    ('<meta content="for internet recorder, record system audio, microphone check, free recording tool, web recorder, audio capture, screen share audio" name="keywords"/>',
     '<meta content="audio recorder, record system sound, microphone recorder, free browser recorder, audio capture" name="keywords"/>'),
    ('<i class="fas fa-toolbox"></i>Utilities</a>',
     '<i class="fas fa-toolbox"></i>Useful tools</a>'),
    ('<span class="breadcrumb-active"><i class="fas fa-microphone-alt"></i>Audio Recorder</span>',
     '<span class="breadcrumb-active"><i class="fas fa-microphone-alt"></i>Audio recorder</span>'),
    ('<h1>Audio Recorder</h1>',
     '<h1>Audio recorder</h1>'),
    ('<div class="subtitle">System audio or microphone &middot; no extra software</div>',
     '<div class="subtitle">System sound or microphone &middot; no extra app needed</div>'),
    ('<span id="statusText">Standby &middot; Ready</span>',
     '<span id="statusText">Standby &middot; Ready</span>'),
    ('<div class="section-label">CURRENT SOURCE</div>',
     '<div class="section-label">CURRENT SOURCE</div>'),
    ('<div class="source-empty">No audio source selected &mdash; click REC and choose to share or allow microphone</div>',
     '<div class="source-empty">No audio source don show yet &mdash; click REC make you choose wetin to share or allow microphone</div>'),
    ('<div class="warn-banner" id="noAudioWarn">⚠ No audio track detected. Make sure to check "Share audio" in di dialog or allow microphone access, then try again.</div>',
     '<div class="warn-banner" id="noAudioWarn">⚠ We no see audio track. Check "Share audio" for the popup or allow microphone, then try again.</div>'),
    ('<span class="setting-label">Audio source</span>',
     '<span class="setting-label">Audio source</span>'),
    ('<option selected="" value="system">🔊 System audio (share &amp; check audio)</option>',
     '<option selected="" value="system">🔊 System sound (share and tick audio)</option>'),
    ('<option value="mic">🎙️ Microphone</option>',
     '<option value="mic">🎙️ Microphone</option>'),
    ('<span class="setting-label">Scheduled stop</span>',
     '<span class="setting-label">Scheduled stop</span>'),
    ('placeholder="0 (manual)"', 'placeholder="0 (manual)"'),
    ('<span class="setting-label">Auto export format</span>',
     '<span class="setting-label">Auto export format</span>'),
    ('<option value="none">Off / keep in list only</option>',
     '<option value="none">Off / keep am only for list</option>'),
    ('<button id="recBtn" onclick="toggleRecording()">',
     '<button id="recBtn" onclick="toggleRecording()">'),
    ('<div class="section-label" style="margin-bottom:0">RECORDINGS</div>',
     '<div class="section-label" style="margin-bottom:0">RECORDINGS</div>'),
    ('<div class="empty-state">No recordings &middot; Press REC and select audio source in di popup</div>',
     '<div class="empty-state">No recording yet &middot; press REC and choose audio source for the popup</div>'),
    ('<div style="color:var(--accent);font-size:10px;letter-spacing:3px;margin-bottom:12px;text-transform:uppercase">⏵ BEFORE YOU START</div>',
     '<div style="color:var(--accent);font-size:10px;letter-spacing:3px;margin-bottom:12px;text-transform:uppercase">⏵ BEFORE YOU START</div>'),
    ('<h2><i class="fas fa-desktop"></i>Browser share dialog explained</h2>',
     '<h2><i class="fas fa-desktop"></i>How the browser share popup dey work</h2>'),
    ('<p style="color:#ccc; margin-bottom:20px;">When you click REC with "System audio" selected, di browser shows dis dialog. Correct operation na crucial.</p>',
     '<p style="color:#ccc; margin-bottom:20px;">When you click REC with "System sound", browser go show this popup. You need use am well make recording work.</p>'),
    ('<div class="title">📋 Dialog mockup (Chrome/Edge)</div>',
     '<div class="title">📋 Popup example (Chrome/Edge)</div>'),
    ('<span>Share</span><span>Cancel</span>',
     '<span>Share</span><span>Cancel</span>'),
    ('<p><i class="fas fa-check-circle" style="color:#4caf50;"></i><strong>Steps:</strong></p>',
     '<p><i class="fas fa-check-circle" style="color:#4caf50;"></i><strong>Steps:</strong></p>'),
    ('<h2><i class="fas fa-question-circle"></i>Frequently Asked Questions</h2>',
     '<h2><i class="fas fa-question-circle"></i>Question wey people dey ask well well</h2>'),
    ('<div class="faq-question">how to record MP3?</div>',
     '<div class="faq-question">How I fit record MP3?</div>'),
    ('<div class="faq-answer">Currently, dis tool supports exporting to WEBM (original quality) and WAV (lossless). If you need MP3 format, we recommend exporting to WAV first and then using our<a class="faq-link" href="/pcm/utility-tools/design-media/audio-converter/">audio converter tool</a>to convert it. We plan to support direct MP3 export in future versions &ndash; stay tuned!</div>',
     '<div class="faq-answer">For now, this tool fit export WEBM and WAV. If you need MP3, export WAV first, then use our <a class="faq-link" href="/pcm/utility-tools/design-media/audio-converter/">audio converter tool</a> turn am to MP3.</div>'),
    ('<div class="faq-question">Use guide am am am am scheduled stop?</div>',
     '<div class="faq-question">How scheduled stop take work?</div>'),
    ('<div style="margin-bottom:6px;">&copy; 2026 StarryRing &middot; For internet Audio Recorder</div>',
     '<div style="margin-bottom:6px;">&copy; 2026 StarryRing &middot; Audio recorder for browser</div>'),
]


RECORDER_JS_REPLACEMENTS = [
    ("Microphone permission denied", "Microphone permission no gree"),
    ("No audio detected, please check \"Share audio\"", "We no hear audio, abeg check \"Share audio\""),
    ("Start failed: ", "Start no work: "),
    ("unknown error", "unknown error"),
    ("Recording started", "Recording don start"),
    ("Recording saved, auto‑exporting as ", "Recording don save, e dey export as "),
    ("Recording saved", "Recording don save"),
    ("Scheduled time reached, stopping...", "Time reach, e dey stop..."),
    ("System audio output", "System sound output"),
    ("System audio · captured via Screen Capture API", "System sound · browser capture am through Screen Capture API"),
    ("No audio source selected — click REC and choose to share or allow microphone", "No audio source don show yet — click REC make you choose wetin to share or allow microphone"),
    ("Standby · Ready", "Standby · Ready"),
    ("Recording · ", "Recording · "),
    ("No recordings · Press REC and select audio source in the popup", "No recording yet · press REC and choose audio source for the popup"),
    ("Play/Pause", "Play/Pause"),
    ("Export", "Export"),
    ("Converting to WAV…", "Dey convert to WAV…"),
    ("WAV export completed", "WAV export don complete"),
    ("WAV conversion failed", "WAV conversion fail"),
    ("Exported .", "Exported ."),
]


FILES = [
    ("pcm/utility-tools/design-media/image-converter/index.html", IMAGE_HTML_REPLACEMENTS),
    ("static/js/utility-tools/design-media/image-converter/script-pcm.js", IMAGE_JS_REPLACEMENTS),
    ("pcm/utility-tools/design-media/audio-converter/index.html", AUDIO_HTML_REPLACEMENTS),
    ("static/js/utility-tools/design-media/audio-converter/script-pcm.js", AUDIO_JS_REPLACEMENTS),
    ("pcm/utility-tools/design-media/online-voice-recorder/index.html", RECORDER_HTML_REPLACEMENTS),
    ("static/js/utility-tools/design-media/online-voice-recorder/script-pcm.js", RECORDER_JS_REPLACEMENTS),
]


def main():
    changed = []
    for path_str, replacements in FILES:
        if replace_all(path_str, replacements):
            changed.append(path_str)
    for path_str in changed:
        print(path_str)


if __name__ == "__main__":
    main()
