from pathlib import Path


ROOT = Path(r"F:\WebTool\toolsite")


def apply_replacements(path_str, replacements):
    path = ROOT / path_str
    text = path.read_text(encoding="utf-8")
    original = text
    for src, dst in replacements:
        text = text.replace(src, dst)
    if text != original:
        path.write_text(text, encoding="utf-8")
        return True
    return False


camera_replacements = [
    ("<title>For internet Webcam Test Tool - Pro Camera Resolution &amp; FPS Tester | StarryRing</title>", "<title>Browser Camera Checker - Sharpness, Resolution &amp; FPS Test | StarryRing</title>"),
    ('<meta content="Preview of di for internet webcam test tool interface" property="og:image:alt"/>', '<meta content="Preview of di browser camera checker screen" property="og:image:alt"/>'),
    ('<meta content="Webcam Test" name="apple-mobile-web-app-title"/>', '<meta content="Camera Checker" name="apple-mobile-web-app-title"/>'),
    ('            "name": "For internet Webcam Test Tool",', '            "name": "Browser Camera Checker",'),
    ('            "description": "Pro for internet camera checking tool with comprehensive performance analysis",', '            "description": "Browser camera checker wey dey test sharpness, resolution, frame rate and device health.",'),
    ('                    "name": "Webcam Test Tool",', '                    "name": "Camera Checker",'),
    ('            "name": "Use guide am am am am di webcam test tool",', '            "name": "How to use di browser camera checker",'),
    ('            "description": "Step-by-step guide to test camera performance, resolution, and frame rate",', '            "description": "Step-by-step guide to test camera sharpness, resolution and frame rate.",'),
    ('                    "name": "Allow camera permission",', '                    "name": "Gree camera permission",'),
    ('                    "text": "When prompted, allow di browser to access your camera. Dis na necessary for di test to work.",', '                    "text": "When browser ask, gree make e use your camera. Na dat one go make di test work.",'),
    ('                    "name": "Select camera device",', '                    "name": "Pick di camera device",'),
    ('                    "text": "If you have multiple cameras connected, choose your camera from di device dropdown menu.",', '                    "text": "If plenty cameras dey connected, choose di one wey you wan test from di device list.",'),
    ('                    "name": "Check di video stream",', '                    "name": "Check di live video",'),
    ('                    "text": "Observe di real-time video to ensure di camera na working properly. Check for blurriness, stuttering, or color issues.",', '                    "text": "Look di live video make you confirm say di camera dey work well. Check blur, shaking or color wahala.",'),
    ('                    "name": "Analyze performance data",', '                    "name": "Read di performance data",'),
    ('                    "text": "View resolution, FPS, and hardware capabilities in di statistics panel. Monitor real-time performance indicators.",', '                    "text": "See resolution, FPS and hardware power for di stats panel. Watch di live numbers as dem dey change.",'),
    ('                    "name": "Test advanced features",', '                    "name": "Try extra features",'),
    ('                    "text": "Try di mirror flip function. If your camera supports it, explore different resolution modes.",', '                    "text": "Try mirror flip. If your camera support am, test different resolution levels too.",'),
    ('            "name": "For internet Webcam Test Tool",', '            "name": "Browser Camera Checker",'),
    ('            "description": "No-pay tool wey you fit use for internet camera check tool for camera performance and resolution testing",', '            "description": "Free browser camera checker for sharpness, resolution and frame-rate testing.",'),
    ('<meta content="No-pay tool wey you fit use for internet webcam test tool. Real-time camera performance testing, resolution check, FPS measurement, hardware capability analysis. No download required. E support laptop cameras, USB cameras, and more." name="description"/>', '<meta content="Free browser camera checker. Test camera sharpness, resolution, FPS and hardware support in real time. No download needed. E support laptop camera, USB camera and more." name="description"/>'),
    ('<meta content="📷 For internet Webcam Test Tool - No-pay Camera Check &amp; Resolution Test" property="og:title"/>', '<meta content="📷 Browser Camera Checker - Free Sharpness, Resolution &amp; FPS Test" property="og:title"/>'),
    ('<meta content="No-pay tool wey you fit use for internet webcam test tool. Real-time camera performance testing, resolution check, FPS measurement. No download required." property="og:description"/>', '<meta content="Free browser camera checker. Test sharpness, resolution and FPS in real time without downloading anything." property="og:description"/>'),
    ('<meta content="📷 For internet Webcam Test Tool - No-pay Camera Check &amp; Resolution Test" name="twitter:title"/>', '<meta content="📷 Browser Camera Checker - Free Sharpness, Resolution &amp; FPS Test" name="twitter:title"/>'),
    ('<meta content="No-pay tool wey you fit use for internet webcam test tool. Real-time camera performance testing, resolution check, FPS measurement. No download required." name="twitter:description"/>', '<meta content="Free browser camera checker. Test sharpness, resolution and FPS in real time without downloading anything." name="twitter:description"/>'),
    ('<meta content="webcam test, camera check, for internet webcam tester, camera resolution test, FPS test, camera performance test, laptop camera check, USB camera check, conference camera check, webcam quality check" name="keywords"/>', '<meta content="camera checker, browser camera test, webcam sharpness test, resolution test, FPS test, laptop camera checker, USB camera checker" name="keywords"/>'),
    ('<span itemprop="name">Tool corner</span>', '<span itemprop="name">Tool area</span>'),
    ('<span class="breadcrumb-active" itemprop="name">Webcam Test Tool</span>', '<span class="breadcrumb-active" itemprop="name">Camera Checker</span>'),
    ('<h1 id="title-text">Pro Webcam Test Tool - Real-time Camera Detection, Resolution/FPS Analysis<span class="badge">No-pay tool wey you fit use for internet</span></h1>', '<h1 id="title-text">Browser Camera Checker - Live Video, Resolution &amp; FPS Test<span class="badge">Free tool for browser</span></h1>'),
    ('<p>No-pay tool wey you fit use for internet webcam test tool, no software installation required. Developed with WebRTC technology, it measures camera performance metrics in real time, including:<strong>video stream quality test</strong>, <strong>resolution detection</strong>, <strong>frame rate (FPS) analysis</strong>, <strong>hardware capability check</strong>. E support various device types:</p>', '<p>Dis browser camera checker no need installation. E use WebRTC take test your camera live, including <strong>video sharpness check</strong>, <strong>resolution detection</strong>, <strong>FPS measurement</strong> and <strong>device capability check</strong>. E support plenty camera types:</p>'),
    ('<span class="keyboard-type-tag">Laptop cameras</span>', '<span class="keyboard-type-tag">Laptop camera</span>'),
    ('<span class="keyboard-type-tag">USB external cameras</span>', '<span class="keyboard-type-tag">USB camera</span>'),
    ('<span class="keyboard-type-tag">Webcams</span>', '<span class="keyboard-type-tag">Webcam</span>'),
    ('<span class="keyboard-type-tag">HD cameras</span>', '<span class="keyboard-type-tag">HD camera</span>'),
    ('<span class="keyboard-type-tag">Conference cameras</span>', '<span class="keyboard-type-tag">Meeting camera</span>'),
    ('<span class="keyboard-type-tag">Live streaming cameras</span>', '<span class="keyboard-type-tag">Streaming camera</span>'),
    ('<span class="keyboard-type-tag">Phone cameras (browser support required)</span>', '<span class="keyboard-type-tag">Phone camera (if browser support am)</span>'),
    ('<i class="fas fa-info-circle"></i><strong>Compatibility note:</strong>Dis tool works with modern browsers like Chrome, Firefox, Edge, Safari, and requires HTTPS environment or localhost access.</div>', '<i class="fas fa-info-circle"></i><strong>Compatibility note:</strong>Dis tool works for modern browsers like Chrome, Firefox, Edge and Safari, and e need HTTPS or localhost.</div>'),
    ('<label for="videoSource" id="video-label">Video Source</label>', '<label for="videoSource" id="video-label">Camera source</label>'),
    ('<button class="secondary" id="btn-mirror">Mirror Flip</button>', '<button class="secondary" id="btn-mirror">Mirror am</button>'),
    ('<h3 id="status-header-text"><span class="status-dot"></span>Device Status</h3>', '<h3 id="status-header-text"><span class="status-dot"></span>Device status</h3>'),
    ('<tr><td id="run-status-label">Status</td><td id="status-text">Requesting permission...</td></tr>', '<tr><td id="run-status-label">Status</td><td id="status-text">Dey ask for permission...</td></tr>'),
    ('<tr><td id="device-name-label">Device Name</td><td id="device-label">-</td></tr>', '<tr><td id="device-name-label">Device name</td><td id="device-label">-</td></tr>'),
    ('<tr><td id="actual-res-label">Actual Resolution</td><td id="info-res">-</td></tr>', '<tr><td id="actual-res-label">Current resolution</td><td id="info-res">-</td></tr>'),
    ('<tr><td id="aspect-ratio-label">Aspect Ratio</td><td id="info-aspect">-</td></tr>', '<tr><td id="aspect-ratio-label">Aspect ratio</td><td id="info-aspect">-</td></tr>'),
    ('<h3 id="caps-header-text" style="margin-top: 20px;">Hardware Capabilities</h3>', '<h3 id="caps-header-text" style="margin-top: 20px;">Hardware power</h3>'),
    ('<div id="caps-hint" style="font-size: 12px; color: var(--text-muted); margin-bottom: 10px;">* Parameters read from browser/driver</div>', '<div id="caps-hint" style="font-size: 12px; color: var(--text-muted); margin-bottom: 10px;">* Browser and driver read dis data</div>'),
    ('<h2>Main advantage of di Webcam Test Tool</h2>', '<h2>Main better side of dis camera checker</h2>'),
    ('<div class="stat-title">Instant Testing</div>', '<div class="stat-title">Instant test</div>'),
    ('<p>See camera parameters immediately</p>', '<p>See camera details immediately</p>'),
    ('<div class="stat-title">Secure</div>', '<div class="stat-title">Safe</div>'),
    ('<p>Data stays local, never uploaded</p>', '<p>Data stay local, e no upload</p>'),
    ('<div class="stat-title">Wide Compatibility</div>', '<div class="stat-title">Broad support</div>'),
    ('<p>E support all camera types</p>', '<p>E support plenty camera types</p>'),
    ('<h2>Pro Webcam Test Tool Wetin e fit do</h2>', '<h2>Wetin dis camera checker fit do</h2>'),
    ("📖 Overview: Di professional webcam test tool offers comprehensive camera checking, from basic video streaming to advanced performance analysis, helping you fully understand your camera's status. E support all camera types, including laptop built-in cameras, USB external cameras, webcams, and more.", "📖 Overview: Dis camera checker gives you full camera test, from basic live video up to deeper performance reading, so you fit know how your camera dey behave. E support laptop camera, USB camera, webcam and more."),
    ('<h3>🔍 Real-time Video Stream Check</h3>', '<h3>🔍 Live video stream check</h3>'),
    ('<p>E show di camera video stream in real time, detecting whether transmission na stable, smooth, and free from stuttering, delay, or frame drops.</p>', '<p>E show your camera live and help you see whether di stream stable, smooth and free from stutter or frame drop.</p>'),
    ('<span class="tip-text">Tip: Observe if di video stream na smooth, without stuttering</span>', '<span class="tip-text">Hint: check whether di live video smooth without shaking</span>'),
    ('<h3>📊 Resolution &amp; Frame Rate Test</h3>', '<h3>📊 Resolution &amp; FPS test</h3>'),
    ('<p>Detect di maximum supported resolution, optimal resolution, and various frame rate modes of di camera, showing real-time resolution and FPS data.</p>', '<p>E detect di best resolution your camera support and show live resolution plus FPS data.</p>'),
    ('<h3>⚙️ Hardware Capability Analysis</h3>', '<h3>⚙️ Hardware capability check</h3>'),
    ("<p>E show di camera's underlying hardware parameters, including supported resolution ranges, frame rate ranges, focus modes, white balance, etc.</p>", '<p>E show deeper camera details like supported resolution range, FPS range, focus mode and white balance.</p>'),
    ('<span class="tip-text">Pay attention to hardware capabilities to understand di camera\'s true performance</span>', '<span class="tip-text">Use di hardware details to judge di real camera strength</span>'),
    ('<h3>🎯 Device Switching &amp; Management</h3>', '<h3>🎯 Device switching</h3>'),
    ('<p>E support switching between multiple camera devices, automatically detecting and listing all available cameras, making it easy to test different devices.</p>', '<p>If plenty camera devices dey, you fit switch between dem quickly and compare results.</p>'),
    ('<span class="tip-text">Switch between cameras for comparative testing</span>', '<span class="tip-text">Switch camera if you want compare two devices</span>'),
    ('<h3>🔄 Mirror Flip Function</h3>', '<h3>🔄 Mirror mode</h3>'),
    ("<p>E give a mirror flip switch to simulate selfie mode, testing di camera's mirror processing capability and display effect.</p>", '<p>E give you mirror mode so you fit check selfie-style view and see how di image display go look.</p>'),
    ('<span class="tip-text">Mirror function na useful for video conferencing and selfies</span>', '<span class="tip-text">Mirror mode dey useful for call and selfie setup</span>'),
    ('<h3>📈 Real-time Performance Monitoring</h3>', '<h3>📈 Live performance watch</h3>'),
    ('<p>E show key parameters like FPS, resolution, and status in real time, allowing quantitative evaluation of camera performance.</p>', '<p>E show key numbers like FPS, resolution and status live so you fit judge performance with real numbers.</p>'),
    ('<span class="tip-text">Data monitoring helps systematically assess camera condition</span>', '<span class="tip-text">Live data fit help you judge whether di camera healthy</span>'),
    ('<h3>Why na my camera not displaying?</h3>', '<h3>Why my camera no show?</h3>'),
    ('Please ensure: 1) You allow di browser to access di camera; 2) Di camera na properly connected; 3) No other application na currently using di camera.', 'Make sure say: 1) you allow browser use di camera; 2) camera connect well; 3) no other app dey use am now.'),
    ('<h3>How do I test camera frame rate?</h3>', '<h3>How I go test camera FPS?</h3>'),
    ('<h3>How fit I tell if my camera quality na poor?</h3>', '<h3>How I go know say camera quality poor?</h3>'),
    ('<h3>What types of cameras na supported?</h3>', '<h3>Which camera types dis tool support?</h3>'),
    ('<h3>How do I test camera resolution?</h3>', '<h3>How I go test camera resolution?</h3>'),
    ('<span class="faq-tip-text">Data security: all data processed locally</span>', '<span class="faq-tip-text">Data safety: everything stay local</span>'),
]


keyboard_replacements = [
    ("<title>Pro For internet Keyboard checker &ndash; NKRO, Chattering &amp; Response Test | Starry Tool</title>", "<title>Browser Keyboard Checker - Chatter, NKRO &amp; Response Test | StarryRing</title>"),
    ('<meta content="For internet keyboard checker interface preview" property="og:image:alt"/>', '<meta content="Preview of di browser keyboard checker layout" property="og:image:alt"/>'),
    ('<meta content="Keyboard check tool" name="apple-mobile-web-app-title"/>', '<meta content="Keyboard Checker" name="apple-mobile-web-app-title"/>'),
    ('                    "name": "Home",', '                    "name": "Home",'),
    ('                    "name": "Tool corner",', '                    "name": "Tool area",'),
    ('                    "name": "Keyboard checker",', '                    "name": "Keyboard checker",'),
    ('            "name": "For internet Keyboard checker",', '            "name": "Browser Keyboard Checker",'),
    ('            "description": "No-pay tool wey you fit use for internet keyboard checker. Detect chattering, double-click, response delay, NKRO (full key rollover) and get repair advice.",', '            "description": "Free browser keyboard checker for chatter, response delay, NKRO and repair hints.",'),
    ('<meta content="No-pay tool wey you fit use for internet keyboard checker. Proly detect key chattering, double-click, response delay and NKRO (full key rollover). Real‑time feedback with diagnosis and repair advice. Start testing your keyboard now!" name="description"/>', '<meta content="Free browser keyboard checker. Test key chatter, double hit, response delay and NKRO with live feedback and repair hints." name="description"/>'),
    ('<meta content="For internet Keyboard checker &ndash; Detect Chattering, NKRO &amp; Response" property="og:title"/>', '<meta content="Browser Keyboard Checker - Chatter, NKRO &amp; Response Test" property="og:title"/>'),
    ('<meta content="No-pay tool wey you fit use for internet keyboard checker. Detect chattering, double‑click, response delay and NKRO. Works with all keyboard types." property="og:description"/>', '<meta content="Free browser keyboard checker. Test chatter, double hit, response delay and NKRO for all keyboard types." property="og:description"/>'),
    ('<meta content="For internet Keyboard checker &ndash; Detect Chattering, NKRO &amp; Response" name="twitter:title"/>', '<meta content="Browser Keyboard Checker - Chatter, NKRO &amp; Response Test" name="twitter:title"/>'),
    ('<meta content="No-pay tool wey you fit use for internet keyboard checker. Detect chattering, double‑click, response delay and NKRO." name="twitter:description"/>', '<meta content="Free browser keyboard checker. Test chatter, double hit, response delay and NKRO." name="twitter:description"/>'),
    ('<meta content="keyboard checker, keyboard check, key chattering test, NKRO test, keyboard response test, mechanical keyboard check, keyboard diagnosis, for internet keyboard check, key press interval, anti-ghosting test" name="keywords"/>', '<meta content="keyboard checker, browser keyboard test, key chatter test, NKRO test, response test, anti-ghosting test" name="keywords"/>'),
    ('<span>Tool corner</span>', '<span>Tool area</span>'),
    ('<h1 id="i18n-h1">For internet Keyboard checker</h1>', '<h1 id="i18n-h1">Browser Keyboard Checker</h1>'),
    ('<p class="lead-text">Pro, free for internet keyboard checker. Quickly perform key detection, chattering test, response delay analysis, and NKRO (full key rollover) diagnosis. Get real‑time professional repair advice.</p>', '<p class="lead-text">Free browser keyboard checker. Test key presses, chatter, response delay and NKRO in real time, plus get quick repair hints.</p>'),
    ('<span>Hint: Press any key on your keyboard to start testing &ndash; di key go highlight in real time. Click di "Diagnosis" button for a professional check.</span>', '<span>Hint: Press any key to start test - di key go light up live. Click "Diagnosis" if you want quick repair hints.</span>'),
    ('<span class="stat-label" id="i18n-tested-keys">Tested Keys</span>', '<span class="stat-label" id="i18n-tested-keys">Keys tested</span>'),
    ('<span class="stat-label" id="i18n-total-strokes">Total Presses</span>', '<span class="stat-label" id="i18n-total-strokes">Total presses</span>'),
    ('<span class="stat-label" id="i18n-active-keys">Concurrent (NKRO)</span>', '<span class="stat-label" id="i18n-active-keys">Keys together (NKRO)</span>'),
    ('<span class="stat-label">Max Concurrent</span>', '<span class="stat-label">Max together</span>'),
    ('<i class="fas fa-lightbulb"></i>Tips</button>', '<i class="fas fa-lightbulb"></i>Hints</button>'),
    ('<i class="fas fa-stethoscope"></i>Diagnosis</button>', '<i class="fas fa-stethoscope"></i>Check am</button>'),
    ('<i class="fas fa-redo"></i>Reset</button>', '<i class="fas fa-redo"></i>Start again</button>'),
    ('<h2>Comprehensive Keyboard check &amp; Diagnosis</h2>', '<h2>Full keyboard check &amp; diagnosis</h2>'),
    ('<p>Dis for internet keyboard checker provides full keyboard diagnostic functions, specifically targeting common issues: key press interval detection, chattering, double‑click, wrong keys, response delay, and NKRO (full key rollover). Our professional detection algorithm helps you quickly locate problems and offers repair advice.</p>', '<p>Dis browser keyboard checker helps you find common keyboard wahala like fast repeat, chatter, double hit, slow response and NKRO limits. E also gives quick repair hints.</p>'),
    ('<h3>Key Press Interval</h3>', '<h3>Key press interval</h3>'),
    ('<h3>Chattering / Double‑click</h3>', '<h3>Chatter / double hit</h3>'),
    ('<h3>Response Delay</h3>', '<h3>Response delay</h3>'),
    ('<h3>NKRO (Full Key Rollover)</h3>', '<h3>NKRO (full rollover)</h3>'),
    ('<h2>How to Use di Keyboard checker</h2>', '<h2>How to use di keyboard checker</h2>'),
    ('<h3>Start Interval Test</h3>', '<h3>Start interval test</h3>'),
    ('<h3>Interpret di Log</h3>', '<h3>Read di log</h3>'),
    ('<h3>Analyze Results</h3>', '<h3>Check di result</h3>'),
    ('<h3>Take Action</h3>', '<h3>Wetin you fit do next</h3>'),
    ('<h2>Keyboard checking FAQ</h2>', '<h2>Keyboard checker FAQ</h2>'),
    ('<h2>Start Your Keyboard check Now</h2>', '<h2>Start your keyboard check now</h2>'),
    ("<p>Na your keyboard suffering from chattering? Don't wait until it affects your work or gaming. Use our professional tester to measure key intervals and spot potential problems early.</p>", "<p>If your keyboard dey misbehave, no wait till e spoil work or game. Use dis tester check key interval and catch problem early.</p>"),
    ('<i class="fas fa-play-circle"></i>Start Test</button>', '<i class="fas fa-play-circle"></i>Start test</button>'),
    ('<i class="fas fa-book"></i>User Guide</a>', '<i class="fas fa-book"></i>Guide</a>'),
    ('<div style="margin-bottom:6px;">&copy; 2026 StarryRing &middot; For internet Keyboard checker</div>', '<div style="margin-bottom:6px;">&copy; 2026 StarryRing &middot; Browser Keyboard Checker</div>'),
]


mic_replacements = [
    ("<title>Microphone check Tool For internet - No-pay Volume, Noise &amp; Latency Detection | StarryRing</title>", "<title>Browser Microphone Checker - Volume, Noise &amp; Delay Test | StarryRing</title>"),
    ('<meta content="For internet microphone check tool interface preview" property="og:image:alt"/>', '<meta content="Preview of di browser microphone checker screen" property="og:image:alt"/>'),
    ('<meta content="Microphone check" name="apple-mobile-web-app-title"/>', '<meta content="Mic Checker" name="apple-mobile-web-app-title"/>'),
    ('            "name": "For internet Microphone check Tool",', '            "name": "Browser Microphone Checker",'),
    ('            "description": "Pro for internet microphone check tool with real-time volume, waveform, frequency, and noise detection.",', '            "description": "Browser microphone checker for live volume, waveform, frequency and noise testing.",'),
    ('            "keywords": "microphone test, online microphone test, audio test, sound card test, Mic test"', '            "keywords": "microphone checker, browser microphone test, audio test, sound card test, mic test"'),
    ('                    "name": "Microphone check Tool",', '                    "name": "Microphone Checker",'),
    ('            "name": "How to Use di Microphone check Tool",', '            "name": "How to use di browser microphone checker",'),
    ('            "description": "Step-by-step guide to testing your microphone volume, noise, latency and performance"', '            "description": "Step-by-step guide to test microphone volume, noise, delay and overall performance."'),
    ('            "name": "Microphone check Tool For internet",', '            "name": "Browser Microphone Checker",'),
    ('            "description": "No-pay tool wey you fit use for internet microphone checking tool for volume, noise and latency detection"', '            "description": "Free browser microphone checker for volume, noise and delay testing."'),
    ('<meta content="No-pay tool wey you fit use for internet microphone checking tool. Pro detection of microphone volume, waveform, frequency, noise, and latency. Real-time audio analysis for USB, Bluetooth, and built-in microphones. No download required." name="description"/>', '<meta content="Free browser microphone checker. Test mic volume, waveform, frequency, noise and delay in real time for USB, Bluetooth and built-in microphones." name="description"/>'),
    ('<meta content="🎤 Microphone check Tool For internet - No-pay Real-time Audio Analysis" property="og:title"/>', '<meta content="🎤 Browser Microphone Checker - Free Real-time Audio Analysis" property="og:title"/>'),
    ('<meta content="No-pay tool wey you fit use for internet microphone checking tool. Pro detection of microphone volume, noise, latency with waveform and spectrum analysis." property="og:description"/>', '<meta content="Free browser microphone checker. Test volume, noise and delay with live waveform and spectrum analysis." property="og:description"/>'),
    ('<meta content="🎤 Microphone check Tool For internet - No-pay Real-time Audio Analysis" name="twitter:title"/>', '<meta content="🎤 Browser Microphone Checker - Free Real-time Audio Analysis" name="twitter:title"/>'),
    ('<meta content="No-pay tool wey you fit use for internet microphone checking tool. Pro detection of microphone volume, noise, latency with waveform and spectrum analysis." name="twitter:description"/>', '<meta content="Free browser microphone checker. Test volume, noise and delay with live waveform and spectrum analysis." name="twitter:description"/>'),
    ('<meta content="microphone check, for internet microphone check, mic test tool, microphone volume detection, microphone noise test, audio latency test, microphone troubleshooting, sound card test, USB microphone check, Bluetooth mic test, laptop microphone check, gaming microphone check, professional audio test" name="keywords"/>', '<meta content="microphone checker, browser mic test, microphone volume test, noise test, audio delay test, USB mic test, Bluetooth mic test" name="keywords"/>'),
    ('<span itemprop="name">Tool corner</span>', '<span itemprop="name">Tool area</span>'),
    ('<span class="breadcrumb-active" itemprop="name">Microphone check Tool</span>', '<span class="breadcrumb-active" itemprop="name">Microphone Checker</span>'),
    ('<h1>For internet Microphone check Tool - No-pay Real-time Audio Analysis</h1>', '<h1>Browser Microphone Checker - Free Live Audio Analysis</h1>'),
    ('<h2>Pro detection of microphone volume, waveform, spectrum, noise, latency</h2>', '<h2>Test microphone volume, waveform, spectrum, noise and delay</h2>'),
    ('<span id="statusText">Initializing...</span>', '<span id="statusText">Dey set things up...</span>'),
    ('<button class="ghost error-btn" id="permBtn" style="display:none">⚠️ Click to allow permission (or reset in address bar)</button>', '<button class="ghost error-btn" id="permBtn" style="display:none">⚠️ Click make you allow permission (or reset am for address bar)</button>'),
    ('<p>Dis tool helps you comprehensively test microphone performance, including:<strong>Real-time volume detection</strong>, <strong>waveform analysis</strong>, <strong>spectrum analysis</strong>, <strong>noise measurement</strong>, <strong>latency test</strong>. E support all types of microphones, including USB microphones, 3.5mm interface microphones, Bluetooth microphones, laptop built-in microphones, etc.</p>', '<p>Dis tool helps you check microphone performance well well, including <strong>live volume detection</strong>, <strong>waveform analysis</strong>, <strong>spectrum analysis</strong>, <strong>noise measurement</strong> and <strong>delay test</strong>. E support USB mic, 3.5mm mic, Bluetooth mic and built-in laptop mic.</p>'),
    ('<span class="keyboard-type-tag">USB Microphone check</span>', '<span class="keyboard-type-tag">USB mic check</span>'),
    ('<span class="keyboard-type-tag">Gaming Microphone check</span>', '<span class="keyboard-type-tag">Gaming mic check</span>'),
    ('<span class="keyboard-type-tag">Laptop Microphone check</span>', '<span class="keyboard-type-tag">Laptop mic check</span>'),
    ('<span class="keyboard-type-tag">Wireless Microphone check</span>', '<span class="keyboard-type-tag">Wireless mic check</span>'),
    ('<span class="keyboard-type-tag">Bluetooth Microphone check</span>', '<span class="keyboard-type-tag">Bluetooth mic check</span>'),
    ('<span class="keyboard-type-tag">Pro Recording Microphone check</span>', '<span class="keyboard-type-tag">Studio mic check</span>'),
    ('<span class="stat-label">Current Volume</span>', '<span class="stat-label">Current volume</span>'),
    ('<span class="stat-label">Peak Volume</span>', '<span class="stat-label">Peak volume</span>'),
    ('<span class="stat-label">Audio Latency</span>', '<span class="stat-label">Audio delay</span>'),
    ('<span class="stat-label">Microphone Status</span>', '<span class="stat-label">Mic status</span>'),
    ('<span class="stat-value" id="micStatusDisplay">Not Connected</span>', '<span class="stat-value" id="micStatusDisplay">No connect</span>'),
    ('<label>Select Microphone</label>', '<label>Choose microphone</label>'),
    ('<label>Input Gain</label>', '<label>Input gain</label>'),
    ('<label style="color:#fff; font-weight:600; text-align:center;">Test Actions</label>', '<label style="color:#fff; font-weight:600; text-align:center;">Test actions</label>'),
    ('<button id="pttBtn">Hold to Record<br/><span style="font-size:12px;font-weight:400;opacity:0.8">Release to Play</span></button>', '<button id="pttBtn">Hold am to record<br/><span style="font-size:12px;font-weight:400;opacity:0.8">Leave am to play back</span></button>'),
    ('<div class="small" style="font-weight:600;margin-bottom:8px">Advanced Options</div>', '<div class="small" style="font-weight:600;margin-bottom:8px">Advanced options</div>'),
    ('<label class="small"><input id="aec" type="checkbox"/>Echo Cancellation (AEC)</label>', '<label class="small"><input id="aec" type="checkbox"/>Echo cancellation (AEC)</label>'),
    ('<label class="small"><input id="autoGain" type="checkbox"/>Auto Gain (AGC)</label>', '<label class="small"><input id="autoGain" type="checkbox"/>Auto gain (AGC)</label>'),
    ('<div class="small">Real-time Waveform</div>', '<div class="small">Live waveform</div>'),
    ('<div class="small">Spectrum Analysis</div>', '<div class="small">Spectrum analysis</div>'),
    ('<div class="stat">Min Noise:<span id="minNoise" style="color:#eab308">-</span> dB</div>', '<div class="stat">Min noise:<span id="minNoise" style="color:#eab308">-</span> dB</div>'),
    ('<div class="stat">Latency:<span id="latencyMs" style="color:var(--latency)">--</span> ms</div>', '<div class="stat">Delay:<span id="latencyMs" style="color:var(--latency)">--</span> ms</div>'),
    ('<h2>Pro Microphone check Tool Wetin e fit do</h2>', '<h2>Wetin dis microphone checker fit do</h2>'),
    ('📖 Intro: Pro microphone check tool provides comprehensive audio detection features, from basic volume testing to advanced spectrum analysis, helping you fully understand microphone status. E support all types of microphones, including USB microphones, 3.5mm interface microphones, laptop built-in microphones, etc.', '📖 Intro: Dis microphone checker gives you full audio test from simple volume check to deeper spectrum reading, so you fit know how your mic dey behave.'),
    ('<h3>🔍 Real-time Volume Detection</h3>', '<h3>🔍 Live volume detection</h3>'),
    ('<h3>⚡ Waveform Analysis</h3>', '<h3>⚡ Waveform check</h3>'),
    ('<h3>⏱️ Spectrum Analysis</h3>', '<h3>⏱️ Spectrum check</h3>'),
    ('<h3>🔧 Latency Test</h3>', '<h3>🔧 Delay test</h3>'),
    ('<h3>🎯 Noise Measurement</h3>', '<h3>🎯 Noise measurement</h3>'),
    ('<h3>📊 Multi-device Support</h3>', '<h3>📊 Multi-device support</h3>'),
    ('<h3>Why na my microphone not working?</h3>', '<h3>Why my microphone no dey work?</h3>'),
    ("Please ensure: 1) You've allowed browser access to di microphone; 2) Correct default input device in system settings; 3) Microphone hardware na properly connected.", 'Make sure say: 1) you allow browser use di microphone; 2) correct input device dey your system settings; 3) microphone connect well.'),
    ('<h3>How to identify microphone issues?</h3>', '<h3>How I go know microphone get problem?</h3>'),
    ('<h3>What types of microphones na supported?</h3>', '<h3>Which microphone types dis tool support?</h3>'),
    ('<h3>How to test microphone latency?</h3>', '<h3>How I go test microphone delay?</h3>'),
    ('<span class="faq-tip-text">Data Security: All audio processing occurs locally</span>', '<span class="faq-tip-text">Data safety: all audio work happen locally</span>'),
    ('<div style="margin-bottom:6px;">&copy; 2026 StarryRing &middot; For internet Microphone check Tool</div>', '<div style="margin-bottom:6px;">&copy; 2026 StarryRing &middot; Browser Microphone Checker</div>'),
]


speaker_replacements = [
    ("<title>Speaker For internet Tester - 10Hz-21kHz Full Frequency Response &amp; Channel Balance Detection</title>", "<title>Browser Speaker Checker - Full Frequency &amp; Channel Balance Test | StarryRing</title>"),
    ('    "name": "Speaker Full Frequency Range Tester",', '    "name": "Browser Speaker Checker",'),
    ('    "featureList": "10Hz-21kHz Full Frequency Test, Frequency Sweep, Channel Balance Test, White Noise/Pink Noise Test",', '    "featureList": "10Hz-21kHz range test, sweep test, channel balance check, white noise and pink noise test",'),
    ('    "description": "Pro for internet speaker testing tool, supporting 10Hz-21kHz frequency sweep, channel balance test, white noise and pink noise tests"', '    "description": "Browser speaker checker with 10Hz-21kHz sweep, channel balance test and noise test."'),
    ('<meta content="Pro for internet speaker testing tool, supporting 10Hz-21kHz frequency sweep, channel balance test, white noise and pink noise tests. Detect frequency response and hardware resonance of speakers, headphones, and home theater systems." name="description"/>', '<meta content="Free browser speaker checker for 10Hz-21kHz sweep, channel balance and noise test. Check frequency response for speakers, headphones and home theater systems." name="description"/>'),
    ('<meta content="Speaker For internet Tester - 10Hz-21kHz Full Frequency Response &amp; Channel Balance Detection" property="og:title"/>', '<meta content="Browser Speaker Checker - Full Frequency &amp; Channel Balance Test" property="og:title"/>'),
    ('<meta content="Pro for internet speaker testing tool, supporting 10Hz-21kHz frequency sweep, channel balance test, white noise and pink noise tests. Detect frequency response and hardware resonance of speakers, headphones, and home theater systems." property="og:description"/>', '<meta content="Free browser speaker checker with 10Hz-21kHz sweep, channel balance and noise test." property="og:description"/>'),
    ('<meta content="Speaker For internet Tester - 10Hz-21kHz Full Frequency Test" name="twitter:title"/>', '<meta content="Browser Speaker Checker - Full Frequency Test" name="twitter:title"/>'),
    ('<meta content="Pro for internet speaker testing tool, supporting 10Hz-21kHz frequency sweep, channel balance test, white noise and pink noise tests." name="twitter:description"/>', '<meta content="Free browser speaker checker with sweep, channel balance and noise test." name="twitter:description"/>'),
    ('<meta content="speaker test, frequency test, audio test, channel balance, sweep test, headphone test, audio analysis, audio testing tool, speaker frequency response, channel balance detection, speaker resonance test, headphone performance evaluation, acoustic measurement for internet tool" name="keywords"/>', '<meta content="speaker checker, browser speaker test, frequency sweep, channel balance test, headphone test, white noise test" name="keywords"/>'),
    ('<span itemprop="name">Tool corner</span>', '<span itemprop="name">Tool area</span>'),
    ('<span class="breadcrumb-active" itemprop="name">Speaker checker</span>', '<span class="breadcrumb-active" itemprop="name">Speaker Checker</span>'),
    ('<h1><i class="fas fa-wave-square"></i>Speaker Full Frequency Range Tester</h1>', '<h1><i class="fas fa-wave-square"></i>Browser Speaker Checker</h1>'),
    ('<p>Dis tool helps you comprehensively test audio device performance, covering the<strong>10Hz - 21kHz</strong>frequency range. E support precise<strong>sine wave generation, sweep analysis, and noise tests</strong>, suitable for speakers, headphones, and professional acoustic systems.</p>', '<p>Dis tool helps you test audio device performance across <strong>10Hz - 21kHz</strong>. E support <strong>sine wave generation, sweep analysis and noise tests</strong> for speakers, headphones and studio setups.</p>'),
    ('<span class="keyboard-type-tag">Speaker Frequency Response</span>', '<span class="keyboard-type-tag">Speaker frequency test</span>'),
    ('<span class="keyboard-type-tag">Headphone Performance Test</span>', '<span class="keyboard-type-tag">Headphone test</span>'),
    ('<span class="keyboard-type-tag">Channel Balance Check</span>', '<span class="keyboard-type-tag">Channel balance</span>'),
    ('<span class="keyboard-type-tag">Resonance Frequency Detection</span>', '<span class="keyboard-type-tag">Resonance check</span>'),
    ('<span class="keyboard-type-tag">Acoustic Environment Assessment</span>', '<span class="keyboard-type-tag">Room sound check</span>'),
    ('<span class="keyboard-type-tag">Audio System Calibration</span>', '<span class="keyboard-type-tag">System calibration</span>'),
    ('<div class="visualizer-label">Real-time Spectrum Analysis</div>', '<div class="visualizer-label">Live spectrum analysis</div>'),
    ('<span>Test Frequency</span>', '<span>Test frequency</span>'),
    ('<button class="freq-btn low" data-freq="20">20Hz <small>Sub-bass</small></button>', '<button class="freq-btn low" data-freq="20">20Hz <small>Deep bass</small></button>'),
    ('<button class="freq-btn low" data-freq="60">60Hz <small>Bass</small></button>', '<button class="freq-btn low" data-freq="60">60Hz <small>Bass</small></button>'),
    ('<button class="freq-btn mid" data-freq="1000">1kHz<small>Reference Mid</small></button>', '<button class="freq-btn mid" data-freq="1000">1kHz<small>Reference mid</small></button>'),
    ('<button class="freq-btn high" data-freq="12000">12kHz<small>Treble</small></button>', '<button class="freq-btn high" data-freq="12000">12kHz<small>Treble</small></button>'),
    ('<button class="freq-btn high" data-freq="18000">18kHz<small>High Treble</small></button>', '<button class="freq-btn high" data-freq="18000">18kHz<small>High treble</small></button>'),
    ('<button class="btn-toggle" id="playStopBtn"><i class="fas fa-play"></i><span id="playStopText">Start Playback</span></button>', '<button class="btn-toggle" id="playStopBtn"><i class="fas fa-play"></i><span id="playStopText">Start playback</span></button>'),
    ('<button class="btn-primary" id="sweepBtn"><i class="fas fa-chart-line"></i>Frequency Sweep (10s)</button>', '<button class="btn-primary" id="sweepBtn"><i class="fas fa-chart-line"></i>Sweep test (10s)</button>'),
    ('<button class="btn-danger" id="stopAllBtn"><i class="fas fa-stop"></i>Stop All</button>', '<button class="btn-danger" id="stopAllBtn"><i class="fas fa-stop"></i>Stop all</button>'),
    ('<i class="fas fa-volume-up" style="margin-right: 8px;"></i>Left Channel</button>', '<i class="fas fa-volume-up" style="margin-right: 8px;"></i>Left side</button>'),
    ('<i class="fas fa-headphones" style="margin-right: 8px;"></i>Both Channels</button>', '<i class="fas fa-headphones" style="margin-right: 8px;"></i>Both sides</button>'),
    ('<i class="fas fa-volume-up" style="margin-right: 8px; transform: scaleX(-1);"></i>Right Channel</button>', '<i class="fas fa-volume-up" style="margin-right: 8px; transform: scaleX(-1);"></i>Right side</button>'),
    ('<i class="fas fa-wave-square" style="margin-right: 8px;"></i>White Noise</button>', '<i class="fas fa-wave-square" style="margin-right: 8px;"></i>White noise</button>'),
    ('<i class="fas fa-wave-square" style="margin-right: 8px; color: #ff99cc;"></i>Pink Noise</button>', '<i class="fas fa-wave-square" style="margin-right: 8px; color: #ff99cc;"></i>Pink noise</button>'),
    ('<div class="status-item"><span class="status-label">Current Frequency</span><span class="status-value" id="currentFrequency">-</span></div>', '<div class="status-item"><span class="status-label">Current frequency</span><span class="status-value" id="currentFrequency">-</span></div>'),
    ('<div class="status-item"><span class="status-label">Channel Mode</span><span class="status-value" id="currentChannel">Both Channels</span></div>', '<div class="status-item"><span class="status-label">Channel mode</span><span class="status-value" id="currentChannel">Both sides</span></div>'),
    ('<div class="status-item"><span class="status-label">Audio Status</span><span class="status-value" id="audioStatus">Inactive</span></div>', '<div class="status-item"><span class="status-label">Audio status</span><span class="status-value" id="audioStatus">No dey run</span></div>'),
    ('<h2>Pro Applications of Speaker checking Tool</h2>', '<h2>Wetin dis speaker checker fit help you do</h2>'),
    ('<h3 itemprop="name">🔧 Audio System Calibration</h3>', '<h3 itemprop="name">🔧 Audio system calibration</h3>'),
    ('<h3 itemprop="name">🎧 Headphone Quality Testing</h3>', '<h3 itemprop="name">🎧 Headphone quality check</h3>'),
    ('<h3 itemprop="name">🏠 Acoustic Environment Assessment</h3>', '<h3 itemprop="name">🏠 Room sound assessment</h3>'),
    ('<span class="tag">Audio Testing Tool</span>', '<span class="tag">Audio testing tool</span>'),
    ('<span class="tag">Speaker Frequency Response Test</span>', '<span class="tag">Speaker frequency test</span>'),
    ('<span class="tag">Channel Balance Detection</span>', '<span class="tag">Channel balance test</span>'),
    ('<span class="tag">Speaker Resonance Test</span>', '<span class="tag">Speaker resonance test</span>'),
    ('<span class="tag">Headphone Performance Evaluation</span>', '<span class="tag">Headphone performance check</span>'),
    ('<span class="tag">Acoustic Measurement For internet Tool</span>', '<span class="tag">Browser acoustic measurement</span>'),
    ('<span class="tag">Sweep Signal Generator</span>', '<span class="tag">Sweep signal generator</span>'),
    ('<span class="tag">White Noise Generator</span>', '<span class="tag">White noise generator</span>'),
    ('<h2>Pro Wetin e fit do of Speaker checking Tool</h2>', '<h2>Wetin dis speaker checker fit do</h2>'),
    ('<p>📖 Dis tool na designed for users seeking audio quality performance, not only testing hardware integrity but also quantitatively evaluating speaker frequency response performance.</p>', '<p>📖 Dis tool no just check whether speaker dey work; e also helps you judge how di speaker respond across frequencies.</p>'),
    ('<h3>🎵 10Hz - 21kHz Full Frequency Coverage</h3>', '<h3>🎵 10Hz - 21kHz full range</h3>'),
    ('<h3>📈 Dynamic Sweep Analysis</h3>', '<h3>📈 Sweep analysis</h3>'),
    ('<h3>🔊 Industrial-Grade Signal Generation</h3>', '<h3>🔊 White and pink noise test</h3>'),
    ('<h3>How to judge speaker quality through testing?</h3>', '<h3>How I go judge speaker quality with dis test?</h3>'),
    ("<h3>Why can't I hear sounds above 18kHz?</h3>", '<h3>Why I no dey hear sound above 18kHz?</h3>'),
    ('<a class="faq-link" href="/pcm/toolbox/speaker/">For internet Hearing Test</a>', '<a class="faq-link" href="/pcm/toolbox/speaker/">Hearing test</a>'),
    ('<strong>Safety Warning:</strong>Do not switch to high-frequency high-volume testing while wearing headphones. Signals below 10Hz may cause excessive driver excursion and damage.</div>', '<strong>Safety warning:</strong>No run high-frequency or loud test while headphone dey your ear. Signals below 10Hz fit overpush driver and cause damage.</div>'),
    ('<div style="margin-bottom:6px;">&copy; 2026 StarryRing &middot; Speaker &amp; Channel Test Tool</div>', '<div style="margin-bottom:6px;">&copy; 2026 StarryRing &middot; Browser Speaker Checker</div>'),
]


camera_js_replacements = [
    ("title.textContent = 'Camera permission request';", "title.textContent = 'Camera permission request';"),
    ("allowButton.textContent = 'Allow access';", "allowButton.textContent = 'Allow access';"),
    ("statusText.textContent = 'Dey wait for your confirmation...';", "statusText.textContent = 'Dey wait make you confirm...';"),
    ("statusText.textContent = 'User no gree give access permission';", "statusText.textContent = 'You no gree give access';"),
    ("window.location.href = '/en/toolbox/';", "window.location.href = '/pcm/toolbox/';"),
    ("option.text = device.label || `Camera ${++videoCount}`;", "option.text = device.label || `Camera ${++videoCount}`;"),
    ("option.text = 'No camera show';", "option.text = 'No camera show';"),
    ("option.text = 'Device listing fail';", "option.text = 'Device list fail';"),
    ("videoElement.setAttribute('aria-label', track.label || 'Camera video stream');", "videoElement.setAttribute('aria-label', track.label || 'Camera live stream');"),
    ("capHtml += `<tr><td>Resolution Range</td><td>${capabilities.width.min} - ${capabilities.width.max}px</td></tr>`;", "capHtml += `<tr><td>Resolution range</td><td>${capabilities.width.min} - ${capabilities.width.max}px</td></tr>`;"),
    ("capHtml += `<tr><td>Height Range</td><td>${capabilities.height.min} - ${capabilities.height.max}px</td></tr>`;", "capHtml += `<tr><td>Height range</td><td>${capabilities.height.min} - ${capabilities.height.max}px</td></tr>`;"),
    ("capHtml += `<tr><td>FPS Range</td><td>${capabilities.frameRate.min} - ${capabilities.frameRate.max}</td></tr>`;", "capHtml += `<tr><td>FPS range</td><td>${capabilities.frameRate.min} - ${capabilities.frameRate.max}</td></tr>`;"),
    ("capHtml += `<tr><td>Supported Ratios</td><td>${capabilities.aspectRatio.min.toFixed(2)} - ${capabilities.aspectRatio.max.toFixed(2)}</td></tr>`;", "capHtml += `<tr><td>Supported ratios</td><td>${capabilities.aspectRatio.min.toFixed(2)} - ${capabilities.aspectRatio.max.toFixed(2)}</td></tr>`;"),
    ("capHtml += `<tr><td>Group ID</td><td title=\"${settings.groupId}\">${settings.groupId.substr(0, 8)}...</td></tr>`;", "capHtml += `<tr><td>Group ID</td><td title=\"${settings.groupId}\">${settings.groupId.substr(0, 8)}...</td></tr>`;"),
    ("capHtml += `<tr><td>Supported Features</td><td>${featureList.join(', ')}</td></tr>`;", "capHtml += `<tr><td>Supported features</td><td>${featureList.join(', ')}</td></tr>`;"),
    ("capHtml += `<tr><td>Current Resolution</td><td>${settings.width}×${settings.height}</td></tr>`;", "capHtml += `<tr><td>Current resolution</td><td>${settings.width}×${settings.height}</td></tr>`;"),
    ("capHtml += `<tr><td>Current Frame Rate</td><td>${settings.frameRate} fps</td></tr>`;", "capHtml += `<tr><td>Current frame rate</td><td>${settings.frameRate} fps</td></tr>`;"),
    ("capTable.innerHTML = capHtml || `<tr><td colspan=\"2\">Unable to get detailed driver information</td></tr>`;", "capTable.innerHTML = capHtml || `<tr><td colspan=\"2\">No fit read detailed driver info</td></tr>`;"),
    ("btn.textContent = isMirrored ? 'Mirror flip' : 'Cancel mirror';", "btn.textContent = isMirrored ? 'Mirror am' : 'Cancel mirror';"),
    ("alert('Your browser no support camera access. Abeg use modern browser like Chrome, Firefox, Edge, or Safari.');", "alert('Your browser no support camera access. Abeg use modern browser like Chrome, Firefox, Edge or Safari.');"),
]


image_converter_js_replacements = [
    ("btnRun.innerHTML = '<i class=\"fas fa-bolt\"></i> Start work';", "btnRun.innerHTML = '<i class=\"fas fa-bolt\"></i> Start work';"),
    ("<i class=\"fas fa-eye\"></i> Original", "<i class=\"fas fa-eye\"></i> Original"),
    ("<i class=\"fas fa-magic\"></i> Result", "<i class=\"fas fa-magic\"></i> Result"),
    ("<i class=\"fas fa-times-circle\"></i> Fail", "<i class=\"fas fa-times-circle\"></i> Fail"),
    ("btnRun.innerHTML = '<i class=\"fas fa-sync-alt\"></i> Run am again';", "btnRun.innerHTML = '<i class=\"fas fa-sync-alt\"></i> Run am again';"),
    ("document.getElementById('modal-tag').innerHTML = `<i class=\"fas fa-search\"></i> ${title}`;", "document.getElementById('modal-tag').innerHTML = `<i class=\"fas fa-search\"></i> ${title}`;"),
]


changes = []
changes.append(apply_replacements("pcm/toolbox/camera/index.html", camera_replacements))
changes.append(apply_replacements("pcm/toolbox/keyboard/index.html", keyboard_replacements))
changes.append(apply_replacements("pcm/toolbox/mic/index.html", mic_replacements))
changes.append(apply_replacements("pcm/toolbox/speaker/index.html", speaker_replacements))
changes.append(apply_replacements("static/js/toolbox/camera/script-pcm.js", camera_js_replacements))
changes.append(apply_replacements("static/js/utility-tools/design-media/image-converter/script-pcm.js", image_converter_js_replacements))

print(f"updated {sum(1 for changed in changes if changed)} files")
