from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def replace_many(path: Path, replacements: list[tuple[str, str]]) -> bool:
    text = path.read_text(encoding="utf-8")
    original = text
    for old, new in replacements:
        text = text.replace(old, new)
    if text != original:
        path.write_text(text, encoding="utf-8")
        return True
    return False


INDEX_REPLACEMENTS = [
    ('<meta content="en" name="content-language"/>', '<meta content="pcm" name="content-language"/>'),
    ("<title>KeyCheck Pro - For internet Mouse &amp; Keyboard checker | Gaming Peripherals Diagnostics</title>",
     "<title>KeyCheck Pro - Browser mouse &amp; keyboard tester wey gamers trust</title>"),
    ('"description": "Professional online mouse and keyboard testing tool for gamers and indie developers to detect input lag, key chatter, and high-frequency click issues."',
     '"description": "Browser tool for gamers and indie developers to check input lag, key chatter, missed taps, and shaky high-speed clicks."'),
    ('"audienceType": "Gamers, Game Developers"',
     '"audienceType": "Gamers and game developers"'),
    ('"name": "What input problems can KeyCheck Pro detect?"',
     '"name": "Wetin KeyCheck Pro fit catch?"'),
    ('"text": "It can detect: 1) Key chatter (single press triggers multiple times) 2) Input lag 3) Key misses 4) Unstable response during high-frequency clicking 5) Key combination conflicts."',
     '"text": "E fit catch key chatter, slow response, missed key press, unstable fast clicking, and key conflict."'),
    ('"name": "Who is this tool for?"',
     '"name": "Who dis tool dey for?"'),
    ('"text": "Primarily for two groups: 1) Gamers - to diagnose peripheral issues during gameplay; 2) Indie game developers - to verify input system stability and distinguish hardware problems from code defects."',
     '"text": "Mainly for gamers wey wan know whether their gear dey fail, and indie developers wey need clean input checks before dem blame their code."'),
    ('"name": "Does the test record my input data?"',
     '"name": "Una dey save my input data?"'),
    ('"text": "No. All testing happens locally in your browser. No input data is recorded or uploaded, ensuring complete privacy."',
     '"text": "No. Everything happen inside your browser. We no save or upload your input data."'),
    ('"name": "Tool box"', '"name": "Home"'),
    ('"description": "A technical tools platform created by gamers and indie developers, focusing on input device testing and game development utilities."',
     '"description": "Tool platform wey gamers and indie developers build to test input devices and handle quick dev tasks."'),
    ('<meta content="KeyCheck Pro na a professional for internet mouse and keyboard checking tool for gamers and developers. Detect input lag, key chatter, click consistency, and device responsiveness directly in your browser." name="description"/>',
     '<meta content="KeyCheck Pro na browser tool wey help gamers and developers test mouse and keyboard response, click stability, and input wahala without install anything." name="description"/>'),
    ('<meta content="KeyCheck Pro - For internet Mouse &amp; Keyboard checker | StarryRing" property="og:title"/>',
     '<meta content="KeyCheck Pro - Browser mouse &amp; keyboard tester | StarryRing" property="og:title"/>'),
    ('<meta content="Pro browser-based mouse and keyboard diagnostics for gamers and developers. Check click consistency, key response, and overall device performance for internet." property="og:description"/>',
     '<meta content="Browser mouse and keyboard diagnostics for gamers and developers. Check click stability, key response, and device performance inside your browser." property="og:description"/>'),
    ('<meta content="KeyCheck Pro - For internet Mouse &amp; Keyboard checker" name="twitter:title"/>',
     '<meta content="KeyCheck Pro - Browser mouse &amp; keyboard tester" name="twitter:title"/>'),
    ('<meta content="Browser-based mouse and keyboard diagnostics for click consistency, key response, and device performance." name="twitter:description"/>',
     '<meta content="Check click stability, key response, and device performance directly inside your browser." name="twitter:description"/>'),
    ('<a href="#about">About</a>', '<a href="#about">Who we be</a>'),
    ('<a href="#utility-tools">utility-tools</a>', '<a href="#utility-tools">Useful tools</a>'),
    ('<span class="tag">🎮 Built by Gamers &middot; Polished for Developers</span>',
     '<span class="tag">🎮 Gamers build am &middot; Developers polish am</span>'),
    ('<h1>When your game feels off,<br/>you need a trustworthy testing tool</h1>',
     '<h1>Any time your game dey feel somehow,<br/>you need testing tool wey you fit trust</h1>'),
    ("<p>I'm a gamer and an indie game developer. While playing, debugging inputs, and fine-tuning controls, I've repeatedly faced di same question:<strong>Na it my mistake, or na my mouse/keyboard faulty?</strong>",
     "<p>I be gamer and indie game developer. As I dey play, debug input, and tune control feel, one question dey always come back:<strong>Na me miss am, or na my mouse/keyboard dey misbehave?</strong>"),
    ('<p>KeyCheck Pro has a simple goal:<strong>Make input problems verifiable, reproducible, and explainable.</strong>',
     '<p>KeyCheck Pro get one simple goal:<strong>Make input wahala easy to confirm, repeat, and explain.</strong>'),
    ('<div class="feature"><i class="fas fa-bolt"></i>Real Input Logging</div>',
     '<div class="feature"><i class="fas fa-bolt"></i>Real input log</div>'),
    ('<div class="feature"><i class="fas fa-chart-line"></i>Data Visualization</div>',
     '<div class="feature"><i class="fas fa-chart-line"></i>Clear data view</div>'),
    ('<a class="btn" href="/pcm/toolbox/">Test My Peripherals</a>',
     '<a class="btn" href="/pcm/toolbox/">Test my gear</a>'),
    ('<h2>A Tool by Gamers, for Gamers</h2>',
     '<h2>Tool wey gamers build for gamers</h2>'),
    ("<p>KeyCheck Pro isn't commercial software; it was born from real frustrations. When input devices become unreliable, both gaming experience and development judgment suffer.</p>",
     "<p>KeyCheck Pro no be random commercial software. Real frustration give birth to am. When input device no stable, both your game feel and your development judgment go suffer.</p>"),
    ('<p>If di input itself cannot be trusted, then all judgments based on it na unreliable.</p>',
     '<p>If you no fit trust the input itself, every conclusion wey come from am go weak.</p>'),
    ('<h2>🚀 Developer Tool corner: Practical Tools to Boost Efficiency</h2>',
     '<h2>🚀 Developer tool corner: small tools wey make work move fast</h2>'),
    ('<p>During game development, beyond core input testing, you also encounter various trivial yet essential tasks:<strong>asset processing, data generation, network debugging, quick generation&hellip;</strong>',
     '<p>During game development, no be only input test you need. Plenty small but important jobs still dey:<strong>asset processing, data generation, network debugging, quick one-click helpers&hellip;</strong>'),
    ("<p>We've integrated a streamlined toolset optimized specifically for game developers, making dese repetitive tasks<strong>fast, simple, and reliable</strong>. </p>",
     "<p>We pack better toolset for game developers so those repeat jobs fit stay<strong>fast, simple, and reliable</strong>. </p>"),
    ('<a class="btn" href="/pcm/utility-tools/">Enter Useful tools</a>',
     '<a class="btn" href="/pcm/utility-tools/">Open useful tools</a>'),
    ('<strong>KeyCheck Pro</strong><br/>An input testing tool built by gamers and indie developers<br/><br/>&copy; 2024 &middot; No-pay to use &middot; No registration &middot; No input data recorded</p>',
     '<strong>KeyCheck Pro</strong><br/>Input testing tool wey gamers and indie developers build<br/><br/>&copy; 2024 &middot; Free to use &middot; No signup &middot; No input data saved</p>'),
]


TOOLBOX_REPLACEMENTS = [
    ('<title>mouse check,keyboard check,camera check,microphone check</title>',
     '<title>Browser hardware check tools for mouse, keyboard, camera and mic</title>'),
    ('"name": "HardwareTest Pro"', '"name": "HardwareTest Pro"'),
    ('"description": "Pro for internet mouse|keyboard|camera|microphone checking tools"',
     '"description": "Browser hardware check tools for mouse, keyboard, camera, microphone, speaker, and screen."'),
    ('<meta content="Pro for internet hardware testing tools - mouse check, mouse click test, double click test, keyboard check, microphone check, camera check. No-pay, no download needed, instant hardware diagnostics solution" name="description"/>',
     '<meta content="Browser hardware test suite for mouse, keyboard, camera, microphone, speaker, and screen. Free to use and no download needed." name="description"/>'),
    ('<meta content="mouse check,keyboard check,camera check,microphone check" property="og:title"/>',
     '<meta content="Browser hardware check tools for mouse, keyboard, camera and mic" property="og:title"/>'),
    ('<meta content="Pro for internet hardware testing tools - mouse check, mouse click test, double click test, keyboard check, microphone check, camera check. No-pay, no download needed, instant hardware diagnostics solution" property="og:description"/>',
     '<meta content="Browser hardware test suite for mouse, keyboard, camera, microphone, speaker, and screen. Free to use and no download needed." property="og:description"/>'),
    ('<meta content="mouse check,keyboard check,camera check,microphone check" name="twitter:title"/>',
     '<meta content="Browser hardware check tools for mouse, keyboard, camera and mic" name="twitter:title"/>'),
    ('<meta content="Pro for internet hardware testing tools - mouse check, mouse click test, double click test, keyboard check, microphone check, camera check. No-pay, no download needed, instant hardware diagnostics solution" name="twitter:description"/>',
     '<meta content="Browser hardware test suite for mouse, keyboard, camera, microphone, speaker, and screen. Free to use and no download needed." name="twitter:description"/>'),
    ('<span class="breadcrumb-active" itemprop="name">Tool corner</span>',
     '<span class="breadcrumb-active" itemprop="name">Toolbox</span>'),
    ('<h1>HardwareTest<span style="font-size: 0.5em; border: 1px solid var(--primary-color); padding: 2px 8px; border-radius: 4px; vertical-align: middle;">PRO</span></h1>',
     '<h1>HardwareTest<span style="font-size: 0.5em; border: 1px solid var(--primary-color); padding: 2px 8px; border-radius: 4px; vertical-align: middle;">PRO</span></h1>'),
    ('>Mouse check<', '>Mouse test<'),
    ('>Keyboard check<', '>Keyboard test<'),
    ('>Camera check<', '>Camera test<'),
    ('>Mic check<', '>Mic test<'),
    ('>Screen check<', '>Screen test<'),
    ('>speaker check<', '>Speaker test<'),
    ('<p class="subtitle">Mouse double-clicking? Keyboard ghosting? Mic too quiet?<br/>No download needed. Pro<span class="highlight">For internet Hardware Lab</span>. </p>',
     '<p class="subtitle">Mouse dey double-click? Keyboard dey ghost? Mic too quiet?<br/>No download needed. Professional<span class="highlight">browser hardware lab</span>. </p>'),
    ('<h3 id="mouse-title">Mouse check Lab</h3>',
     '<h3 id="mouse-title">Mouse test lab</h3>'),
    ('<p>Millisecond-level switch analysis. Real-time Polling Rate, scroll wheel &amp; side button tests. Fix double-click issues.</p>',
     '<p>Millisecond switch analysis, real-time polling rate, scroll wheel, and side button checks to help you trace double-click wahala.</p>'),
    ('>Start Mouse check<', '>Start mouse test<'),
    ('<p>Full-key rollover &amp; conflict test. Integrated repair guide for ghosting and unresponsive keys.</p>',
     '<p>Full-key rollover and conflict check with quick repair hints for ghosting and dead or stubborn keys.</p>'),
    ('>Launch Keyboard check<', '>Open keyboard test<'),
    ('>Apple Keyboard check<', '>Apple keyboard test<'),
    ('<h3 id="av-title">A/V Diagnostics</h3>',
     '<h3 id="av-title">Audio and video checks</h3>'),
    ('<p>One-click webcam &amp; mic check. Detailed resolution, frame rate &amp; waveform analysis. Mobile &amp; PC supported.</p>',
     '<p>One-click webcam and mic check with resolution, frame rate, and waveform details. Phone and PC both dey supported.</p>'),
    ('>Webcam Test<', '>Webcam check<'),
    ('<h2 class="docs-title">HardwareTest User Manual &amp; Wetin e fit do</h2>',
     '<h2 class="docs-title">HardwareTest guide and wetin e fit do</h2>'),
    ('<button class="docs-toggle" id="docsToggle">View User Manual</button>',
     '<button class="docs-toggle" id="docsToggle">See guide</button>'),
    ('<p>HardwareTest na a professional for internet hardware testing toolset designed to help users quickly diagnose and resolve common computer peripheral issues. No software installation required - complete comprehensive hardware testing directly in your browser.</p>',
     '<p>HardwareTest na browser hardware test set wey help people quickly find and understand common computer peripheral wahala. No software install needed.</p>'),
    ('<h4>Mouse checking Wetin e fit do</h4>',
     '<h4>Wetin mouse test fit do</h4>'),
    ('<p>Comprehensive testing of all mouse functions including left/right clicks, scroll wheel, DPI switching, and side buttons. Specialized detection for common double-click issues.</p>',
     '<p>E check left and right click, scroll wheel, DPI switch, and side buttons, plus special checks for common double-click trouble.</p>'),
    ('<li>Left/right click response testing</li>', '<li>Left and right click response check</li>'),
    ('<li>Scroll wheel sensitivity and direction detection</li>', '<li>Scroll wheel sensitivity and direction check</li>'),
    ('<li>DPI switching function verification</li>', '<li>DPI switch verification</li>'),
    ('<li>Side button functionality check</li>', '<li>Side button function check</li>'),
    ('<h4>Keyboard checking Wetin e fit do</h4>',
     '<h4>Wetin keyboard test fit do</h4>'),
    ('<p>Full key functionality testing including key conflict detection, key chattering analysis, and function key verification. E support various mechanical and membrane keyboard layouts.</p>',
     '<p>E test full keyboard function, key conflict, key chatter, and function keys across mechanical and membrane layouts.</p>'),
    ('<li>Full key functionality test</li>', '<li>Full key function check</li>'),
    ('<li>Key conflict detection</li>', '<li>Key conflict check</li>'),
    ('<li>Key chattering analysis</li>', '<li>Key chatter analysis</li>'),
    ('<li>Function key and combination verification</li>', '<li>Function key and shortcut verification</li>'),
    ('<h4>Camera checking Wetin e fit do</h4>',
     '<h4>Wetin camera test fit do</h4>'),
    ('<p>Comprehensive camera status detection including resolution, frame rate, autofocus, and color accuracy. E support front and rear camera switching tests.</p>',
     '<p>E inspect camera status with resolution, frame rate, autofocus, and color checks, plus front and rear camera switching.</p>'),
    ('<li>Resolution and image quality detection</li>', '<li>Resolution and image quality check</li>'),
    ('<li>Frame rate and smoothness testing</li>', '<li>Frame rate and smoothness check</li>'),
    ('<li>Autofocus function verification</li>', '<li>Autofocus verification</li>'),
    ('<li>Color accuracy analysis</li>', '<li>Color accuracy analysis</li>'),
    ('<h4>Microphone checking Wetin e fit do</h4>',
     '<h4>Wetin mic test fit do</h4>'),
    ('<p>Precise microphone status detection including sensitivity testing, noise analysis, and audio quality assessment. E give real-time waveform visualization.</p>',
     '<p>E check microphone sensitivity, background noise, and audio quality, and show live waveform while you dey talk.</p>'),
    ('<li>Microphone sensitivity testing</li>', '<li>Microphone sensitivity check</li>'),
    ('<li>Background noise analysis</li>', '<li>Background noise analysis</li>'),
    ('<li>Audio quality assessment</li>', '<li>Audio quality check</li>'),
    ('<li>Real-time waveform visualization</li>', '<li>Live waveform view</li>'),
    ('<h4>Screen Dead Pixel Detection Wetin e fit do</h4>',
     '<h4>Wetin screen dead-pixel test fit do</h4>'),
    ('<p>Offers a professional full-screen solid color detection mode, which fit be used to identify bright spots, dead pixels, light leaks, and uneven color. E support multiple color switching modes, coupled with anti-interference and anti-shake design, ensuring stable and reliable testing.</p>',
     '<p>E gives full-screen solid color mode to spot bright dots, dead pixels, light leak, and uneven color, with steady switching between many test colors.</p>'),
    ('<li>Full-screen solid color dead pixel detection</li>', '<li>Full-screen dead-pixel check with solid colors</li>'),
    ('<li>Offers 8 color switching options</li>', '<li>Eight color switching options</li>'),
    ('<li>Test mode automatically hides di mouse and interface</li>', '<li>Test mode hides mouse and interface by itself</li>'),
    ('<li>E support exiting with ESC and automatically restoring di interface</li>', '<li>ESC fit close am and restore the interface</li>'),
    ('<h3 style="color: var(--primary-color); margin-bottom: 15px;">Frequently Asked Questions</h3>',
     '<h3 style="color: var(--primary-color); margin-bottom: 15px;">Common questions</h3>'),
    ('<p><strong>Q: Do dese testing tools require any software installation?</strong></p>',
     '<p><strong>Q: Do I need install software before I use am?</strong></p>'),
    ('<p>A: Not at all! HardwareTest na a web-based for internet tool dat works directly in modern browsers like Chrome, Firefox, Edge, etc.</p>',
     '<p>A: No. HardwareTest na browser tool wey works straight inside Chrome, Firefox, Edge, and other modern browsers.</p>'),
    ('<p><strong>Q: Na di test results accurate?</strong></p>',
     '<p><strong>Q: Di result fit be trusted?</strong></p>'),
    ('<p>A: Our tools use professional testing algorithms dat accurately reflect hardware status. Note dat some advanced features may require specific browser permissions.</p>',
     '<p>A: Our tools use proper testing logic to show wetin your hardware dey do. Some advanced features may still need browser permission.</p>'),
    ('<p><strong>Q: Does it support mobile devices?</strong></p>',
     '<p><strong>Q: E fit work for phone and tablet too?</strong></p>'),
    ('<p>A: Yes! HardwareTest fully supports smartphones and tablets, allowing you to test mobile device cameras, microphones, and other functions.</p>',
     '<p>A: Yes. HardwareTest supports phone and tablet well, so you fit test camera, microphone, and other hardware there too.</p>'),
    ('<p>&copy; 2023 HardwareTest Tools Official. All Systems Operational.</p>',
     '<p>&copy; 2023 HardwareTest Tools. All systems dey ready.</p>'),
]


ABOUT_REPLACEMENTS = [
    ('<title>StarryRing &ndash; input tester for gamers &amp; developers</title>',
     '<title>About StarryRing &ndash; browser input checks for gamers and developers</title>'),
    ('<meta content="Learn why StarryRing was built for gamers and developers who need fast, trustworthy keyboard and mouse diagnostics in a clean browser-based environment." name="description"/>',
     '<meta content="Learn why StarryRing build browser input-check tools for gamers and developers wey need fast, trustworthy keyboard and mouse diagnostics." name="description"/>'),
    ('<meta content="StarryRing &ndash; input tester for gamers &amp; developers" property="og:title"/>',
     '<meta content="About StarryRing &ndash; browser input checks for gamers and developers" property="og:title"/>'),
    ('<meta content="Learn why StarryRing was built for gamers and developers who need fast, trustworthy keyboard and mouse diagnostics in a clean browser-based environment." property="og:description"/>',
     '<meta content="Learn why StarryRing build browser input-check tools for gamers and developers wey need fast, trustworthy keyboard and mouse diagnostics." property="og:description"/>'),
    ('<meta content="StarryRing &ndash; input tester for gamers &amp; developers" name="twitter:title"/>',
     '<meta content="About StarryRing &ndash; browser input checks for gamers and developers" name="twitter:title"/>'),
    ('<meta content="Learn why StarryRing was built for gamers and developers who need fast, trustworthy keyboard and mouse diagnostics in a clean browser-based environment." name="twitter:description"/>',
     '<meta content="Learn why StarryRing build browser input-check tools for gamers and developers wey need fast, trustworthy keyboard and mouse diagnostics." name="twitter:description"/>'),
    ('<p class="text-slate-400 text-lg">Every millisecond of precision na our respect for players.</p>',
     '<p class="text-slate-400 text-lg">Every millisecond of precision na respect wey we dey show players.</p>'),
    ('<h2 class="text-2xl font-semibold mb-4 text-blue-300">Why StarryRing?</h2>',
     '<h2 class="text-2xl font-semibold mb-4 text-blue-300">Why StarryRing dey here?</h2>'),
    ("<p class=\"text-slate-400 leading-relaxed\">I'm an independent game developer and a long‑time gamer. While building game input systems and testing hardware response, I often ran into issues like unresponsive keyboard keys, erratic mouse double‑clicks, dropped clicks, dragging failures, and unstable scrolling.<strong>The worst part? I could never be sure whether it was actually a hardware problem with di mouse or keyboard.</strong>To isolate di issue, I needed a clean, distraction‑free testing environment &mdash; so dis website was born.<br/><br/>StarryRing</p>",
     "<p class=\"text-slate-400 leading-relaxed\">I be independent game developer and long-time gamer. As I dey build input systems and test hardware response, I dey always jam wahala like key wey no answer, mouse wey dey double-click anyhow, dropped clicks, drag failures, and unstable scrolling.<strong>Worst part be say I no fit always tell whether na real hardware problem or something else cause am.</strong>To separate the issue cleanly, I need testing space wey no get distraction &mdash; na so dis website take show face.<br/><br/>StarryRing</p>"),
    ('<li class="flex items-center"><span class="w-2 h-2 bg-blue-500 rounded-full mr-3"></span>100% browser native API calls</li>',
     '<li class="flex items-center"><span class="w-2 h-2 bg-blue-500 rounded-full mr-3"></span>100% native browser API calls</li>'),
    ('<li class="flex items-center"><span class="w-2 h-2 bg-purple-500 rounded-full mr-3"></span>Zero third‑party tracking scripts</li>',
     '<li class="flex items-center"><span class="w-2 h-2 bg-purple-500 rounded-full mr-3"></span>No third-party tracking scripts</li>'),
    ('<li class="flex items-center"><span class="w-2 h-2 bg-pink-500 rounded-full mr-3"></span>Strong visual feedback for every action</li>',
     '<li class="flex items-center"><span class="w-2 h-2 bg-pink-500 rounded-full mr-3"></span>Clear visual feedback for every action</li>'),
    ('<h3 class="font-bold mb-2">Lightning Fast</h3>',
     '<h3 class="font-bold mb-2">Fast no be small</h3>'),
    ('<p class="text-xs text-slate-500">Instant feedback on test data.</p>',
     '<p class="text-xs text-slate-500">You go see result sharp-sharp.</p>'),
    ('<h3 class="font-bold mb-2">Transparent Privacy</h3>',
     '<h3 class="font-bold mb-2">Privacy clear well</h3>'),
    ('<p class="text-xs text-slate-500">We never upload any input data &mdash; everything runs locally.</p>',
     '<p class="text-xs text-slate-500">We no upload your input data &mdash; everything runs locally.</p>'),
    ('<h3 class="font-bold mb-2">Developer Friendly</h3>',
     '<h3 class="font-bold mb-2">Developer-friendly</h3>'),
    ('<p class="text-xs text-slate-500">Raw, direct data for hardcore gamers and peripheral developers.</p>',
     '<p class="text-xs text-slate-500">Raw direct data for serious gamers and peripheral developers.</p>'),
]


CONTACT_REPLACEMENTS = [
    ('<title>Contact &middot; Starry Ring</title>',
     '<title>Reach StarryRing &middot; Contact page</title>'),
    ('<meta content="Contact di StarryRing team for bug reports, feedback, feature ideas, or developer collaboration through email, GitHub, or Discord." name="description"/>',
     '<meta content="Reach the StarryRing team for bug report, feedback, feature idea, or developer collaboration through email, GitHub, or Discord." name="description"/>'),
    ('<meta content="Contact &middot; Starry Ring" property="og:title"/>',
     '<meta content="Reach StarryRing &middot; Contact page" property="og:title"/>'),
    ('<meta content="Contact di StarryRing team for bug reports, feedback, feature ideas, or developer collaboration through email, GitHub, or Discord." property="og:description"/>',
     '<meta content="Reach the StarryRing team for bug report, feedback, feature idea, or developer collaboration through email, GitHub, or Discord." property="og:description"/>'),
    ('<meta content="Contact &middot; Starry Ring" name="twitter:title"/>',
     '<meta content="Reach StarryRing &middot; Contact page" name="twitter:title"/>'),
    ('<meta content="Contact di StarryRing team for bug reports, feedback, feature ideas, or developer collaboration through email, GitHub, or Discord." name="twitter:description"/>',
     '<meta content="Reach the StarryRing team for bug report, feedback, feature idea, or developer collaboration through email, GitHub, or Discord." name="twitter:description"/>'),
    ('<h2 class="text-3xl font-bold mb-2">Stay in Touch 🛰️</h2>',
     '<h2 class="text-3xl font-bold mb-2">Make we hear from you 🛰️</h2>'),
    ('<p class="text-slate-400 mb-8">Encounter a bug? Or want to chat about game development? Feel free to reach out.</p>',
     '<p class="text-slate-400 mb-8">You see bug? Or you wan yarn about game development? Reach us any time.</p>'),
    ('<p class="text-xs text-slate-500 uppercase tracking-widest">Official Email</p>',
     '<p class="text-xs text-slate-500 uppercase tracking-widest">Official email</p>'),
    ('<button class="opacity-0 group-hover:opacity-100 text-xs bg-slate-700 px-3 py-1 rounded text-slate-300">Copy</button>',
     '<button class="opacity-0 group-hover:opacity-100 text-xs bg-slate-700 px-3 py-1 rounded text-slate-300">Copy am</button>'),
    ('<!-- Discord Invite -->', '<!-- Discord invite -->'),
    ('<!-- QR code image path remains unchanged; alt text updated to English -->', '<!-- QR code image path stays the same -->'),
    ('<img alt="Discord QR Code" class="w-20 h-20 object-cover rounded-lg" src="/static/image/zh/contact-discord.png"/>',
     '<img alt="Discord QR code" class="w-20 h-20 object-cover rounded-lg" src="/static/image/zh/contact-discord.png"/>'),
    ('<footer class="mt-12 pt-8 border-t border-slate-800 text-center text-slate-500 text-sm">Currently maintained by a solo developer, replies may be slightly delayed. Thank you for your understanding.<div class="mt-4 pt-4 border-t border-slate-700 space-x-3">',
     '<footer class="mt-12 pt-8 border-t border-slate-800 text-center text-slate-500 text-sm">Na one developer still dey maintain dis place, so reply fit delay small. Thanks for understanding.<div class="mt-4 pt-4 border-t border-slate-700 space-x-3">'),
]


FILES = {
    ROOT / "pcm" / "index.html": INDEX_REPLACEMENTS,
    ROOT / "pcm" / "toolbox" / "index.html": TOOLBOX_REPLACEMENTS,
    ROOT / "pcm" / "about-us" / "index.html": ABOUT_REPLACEMENTS,
    ROOT / "pcm" / "contact-us" / "index.html": CONTACT_REPLACEMENTS,
}


def main():
    for path, replacements in FILES.items():
        if replace_many(path, replacements):
            print(path.relative_to(ROOT).as_posix())


if __name__ == "__main__":
    main()
